import type { Database, QueryContext } from '../../infrastructure/database/Database.js';
import type { RoomEvent } from '../../types.js';
import {toRoomEvent} from '../../infrastructure/database/rowMappers.js';

export class RoomEventRepository {
  constructor(private readonly database:Database){}
  async append(roomId:string,type:string,payload:unknown){return this.database.transaction(tx=>this.appendProjectedInTransaction(tx,roomId,type,payload,new Date().toISOString()));}
  async appendProjectedInTransaction(db:QueryContext,roomId:string,type:string,payload:unknown,createdAt:string){const runId=payload&&typeof payload==='object'&&typeof(payload as {runId?:unknown}).runId==='string'?(payload as {runId:string}).runId:undefined;if(runId&&type==='run.delta')await db`UPDATE agent_runs SET text=text||${String((payload as {text?:unknown}).text??'')},updated_at=now() WHERE id=${runId}`;if(runId&&type==='run.reasoning.delta')await db`UPDATE agent_runs SET reasoning=reasoning||${String((payload as {text?:unknown}).text??'')},updated_at=now() WHERE id=${runId}`;if(runId&&type==='run.upstream_status'){const state=(payload as {state?:unknown}).state;await db`UPDATE agent_runs SET upstream_status=${state==='recovered'?null:this.database.sql.json(withoutRunId(payload) as never)},updated_at=now() WHERE id=${runId}`;}if(runId&&type==='run.status'){const status=String((payload as {status?:unknown}).status??''),error=typeof(payload as {error?:unknown}).error==='string'?(payload as {error:string}).error:null,errorCode=typeof(payload as {errorCode?:unknown}).errorCode==='string'?(payload as {errorCode:string}).errorCode:null;if(['completed','failed','cancelled'].includes(status))await db`UPDATE agent_runs SET status=${status},upstream_status=NULL,error=${error},error_code=${errorCode},updated_at=now() WHERE id=${runId}`;else await db`UPDATE agent_runs SET status=${status},error=${error},error_code=${errorCode},updated_at=now() WHERE id=${runId}`;if(status==='completed')await db`UPDATE response_slots SET selected_run_id=${runId} WHERE id=(SELECT response_slot_id FROM agent_runs WHERE id=${runId})`;}return this.appendInTransaction(db,roomId,type,payload,createdAt);}
  async appendInTransaction(db:QueryContext,roomId:string,type:string,payload:unknown,createdAt:string){const [{event_sequence}]=await db`UPDATE rooms SET event_sequence=event_sequence+1 WHERE id=${roomId} RETURNING event_sequence`;const id=crypto.randomUUID(),event={id,event_id:id,sequence:Number(event_sequence),type,payload};await db`INSERT INTO room_events VALUES(${id},${id},${roomId},${event.sequence},${type},${this.database.sql.json(payload as never)},${createdAt})`;return event;}
  async replay(roomId:string,after:number):Promise<RoomEvent[]>{return(await this.database.sql`SELECT id,event_id,sequence,type,payload FROM room_events WHERE room_id=${roomId} AND sequence>${after} ORDER BY sequence`).map(toRoomEvent);}
}

function withoutRunId(payload:unknown){if(!payload||typeof payload!=='object'||Array.isArray(payload))return{};const{runId:_runId,...status}=payload as Record<string,unknown>;return status;}
