import { describe, expect, it } from 'vitest';
import { fakePersonas, type Persona } from '../../../entities/persona';
import { activeMentionQuery, insertMentionAt, parseMentions, removeMentionTarget } from './mentions';

describe('parseMentions',()=>{it('parses supplied handles case-insensitively and deduplicates',()=>expect(parseMentions('@Coder hi @coder, @architect',fakePersonas)).toEqual(['coder','architect']));it('expands @all in supplied room order',()=>expect(parseMentions('ask @all please',fakePersonas)).toEqual(['architect','coder','reviewer','debugger']));it('ignores aliases, email fragments and unknown handles',()=>expect(parseMentions('@qwen a@coder.dev @unknown',fakePersonas)).toEqual([]));});
describe('mention autocomplete query',()=>{it('finds a mention at the caret with its replacement range',()=>expect(activeMentionQuery('ask @arc please',8)).toEqual({start:4,end:8,query:'arc'}));it('opens for an empty @ token',()=>expect(activeMentionQuery('hello @',7)).toEqual({start:6,end:7,query:''}));it('does not open inside an email address',()=>expect(activeMentionQuery('a@code',6)).toBeUndefined());});
describe('active persona inputs',()=>{it('retains archived identities in the full catalog but excludes them from dynamic mentions',()=>{const archived:Persona={id:'old',handle:'old',name:'Old',color:'#000',requested_model:'sol',harness_instance_id:'local-hermes',harness_type:'hermes',model_id:'sol',permission_profile_id:null,agent_variant_id:null,default_reasoning_effort:null,group_id:null,archived_at:'2026-01-01'};const catalog:Persona[]=[...fakePersonas,archived];const active=catalog.filter(persona=>!persona.archived_at);expect(catalog.find(persona=>persona.handle==='old')).toBe(archived);expect(active.find(persona=>persona.handle==='old')).toBeUndefined();expect(parseMentions('@all @old',active)).toEqual(['architect','coder','reviewer','debugger'])})});
describe('insertMentionAt',()=>{it('inserts at the caret with readable spacing',()=>{expect(insertMentionAt('Спроси пожалуйста', 'coder',7,7)).toEqual({text:'Спроси @coder пожалуйста',caret:14});expect(insertMentionAt('','coder')).toEqual({text:'@coder ',caret:7})})});
describe('removeMentionTarget',()=>{it('expands @all into the remaining explicit handles',()=>expect(removeMentionTarget('ask @all please','coder',fakePersonas)).toBe('ask @architect @reviewer @debugger please'));it('removes the target even when it is also mentioned explicitly',()=>expect(removeMentionTarget('@all and @coder','coder',fakePersonas)).toBe('@architect @reviewer @debugger and '));it('removes a regular explicit mention without flattening line breaks',()=>expect(removeMentionTarget('ask @coder\nthen continue','coder',fakePersonas)).toBe('ask\nthen continue'));it('removes @all when it was the only available target',()=>expect(removeMentionTarget('ask @all please','solo',[{handle:'solo'}])).toBe('ask please'))});
