import type {Database} from '../../infrastructure/database/Database.js';
import type {PersonaGroup} from '../../types.js';
import {number,toPersonaGroup} from '../../infrastructure/database/rowMappers.js';

export class PersonaGroupRepository{
  constructor(private readonly database:Database){}
  async list():Promise<PersonaGroup[]>{return(await this.database.sql`SELECT * FROM persona_groups ORDER BY position,name`).map(toPersonaGroup);}
  async create(name:string){const now=new Date().toISOString(),id=crypto.randomUUID();return this.database.transaction(async tx=>{const [{position}]=await tx`SELECT COALESCE(MAX(position),-1)::int+1 position FROM persona_groups`;const [group]=await tx`INSERT INTO persona_groups(id,name,position,created_at,updated_at) VALUES(${id},${name},${number(position)},${now},${now}) RETURNING *`;return toPersonaGroup(group);});}
  async rename(id:string,name:string){const [group]=await this.database.sql`UPDATE persona_groups SET name=${name},updated_at=now() WHERE id=${id} RETURNING *`;return group?toPersonaGroup(group):undefined;}
  async move(id:string,direction:'up'|'down'){return this.database.transaction(async tx=>{const [current]=await tx`SELECT * FROM persona_groups WHERE id=${id} FOR UPDATE`;if(!current)return'not_found' as const;const currentPosition=number(current.position);const adjacent=direction==='up'?(await tx`SELECT * FROM persona_groups WHERE position < ${currentPosition} ORDER BY position DESC LIMIT 1 FOR UPDATE`)[0]:(await tx`SELECT * FROM persona_groups WHERE position > ${currentPosition} ORDER BY position LIMIT 1 FOR UPDATE`)[0];if(!adjacent)return'boundary' as const;const adjacentPosition=number(adjacent.position),temporary=-1-currentPosition;await tx`UPDATE persona_groups SET position=${temporary} WHERE id=${id}`;await tx`UPDATE persona_groups SET position=${currentPosition},updated_at=now() WHERE id=${String(adjacent.id)}`;const [moved]=await tx`UPDATE persona_groups SET position=${adjacentPosition},updated_at=now() WHERE id=${id} RETURNING *`;return toPersonaGroup(moved);});}
  async reorder(id:string,targetPosition:number){return this.database.transaction(async tx=>{const rows=await tx`SELECT * FROM persona_groups ORDER BY position,name FOR UPDATE`;const from=rows.findIndex(row=>String(row.id)===id);if(from<0)return'not_found' as const;if(targetPosition<0||targetPosition>=rows.length)return'out_of_range' as const;if(from===targetPosition)return toPersonaGroup(rows[from]);const ordered=[...rows];const [moved]=ordered.splice(from,1);ordered.splice(targetPosition,0,moved);await tx`UPDATE persona_groups SET position=-(position+1)`;for(let position=0;position<ordered.length;position++)await tx`UPDATE persona_groups SET position=${position},updated_at=now() WHERE id=${String(ordered[position].id)}`;const [result]=await tx`SELECT * FROM persona_groups WHERE id=${id}`;return toPersonaGroup(result);});}
  async delete(id:string){return this.database.transaction(async tx=>{const [group]=await tx`DELETE FROM persona_groups WHERE id=${id} RETURNING position`;if(!group)return false;await tx`UPDATE persona_groups SET position=position-1,updated_at=now() WHERE position>${group.position as number}`;return true;});}
}
