import {useEffect,useRef,useState} from 'react';
import {ChevronRight,Plus} from 'lucide-react';
import {HarnessIcon,personaModelName,type HarnessCatalog} from '../../entities/harness';
import type {Persona} from '../../entities/persona';
import type {PersonaGroup} from '../../entities/persona-group';
import type {LocalProject,Room,RoomPersona} from '@agenvyl/contracts';
import {ReasoningEffortChip} from '../reasoning-effort';
import {Alert,Avatar,Button,Dialog} from '../../shared/ui';
import styles from './RoomDialogs.module.css';

function GroupCheckbox({items,label,selected,onToggle}:{items:Persona[];label:string;selected:Set<string>;onToggle:()=>void}){const ref=useRef<HTMLInputElement>(null);const count=items.filter(item=>selected.has(item.id)).length;useEffect(()=>{if(ref.current)ref.current.indeterminate=count>0&&count<items.length},[count,items.length]);return <input ref={ref} type="checkbox" aria-label={`Select the entire ${label} group`} checked={Boolean(items.length)&&count===items.length} onChange={onToggle}/>}
function GroupedOptions({personas,catalog,groups,selected,onToggle,roomPersonas=[],onUpdateReasoning}:{personas:Persona[];catalog?:HarnessCatalog;groups:PersonaGroup[];selected:Set<string>;onToggle:(id:string)=>void;roomPersonas?:RoomPersona[];onUpdateReasoning?:(personaId:string,value:string|null)=>Promise<unknown>}){
  const sections=[...groups.map(group=>({id:group.id,name:group.name,items:personas.filter(p=>p.group_id===group.id)})),{id:'ungrouped',name:'Ungrouped',items:personas.filter(p=>!p.group_id)}].filter(section=>section.items.length);
  const roomMap=new Map(roomPersonas.map(item=>[item.persona.id,item]));
  const [collapsed,setCollapsed]=useState(()=>new Set(sections.filter(section=>!section.items.some(persona=>selected.has(persona.id))).map(section=>section.id)));
  const toggleCollapsed=(id:string)=>setCollapsed(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next});
  return <>{sections.map(section=>{
    const all=section.items.every(persona=>selected.has(persona.id));
    const closed=collapsed.has(section.id);
    return <section className={styles.agentGroup} key={section.id}>
      <header>
        <GroupCheckbox items={section.items} label={section.name} selected={selected} onToggle={()=>section.items.forEach(persona=>{if(all?selected.has(persona.id):!selected.has(persona.id))onToggle(persona.id)})}/>
        <button type="button" className={styles.groupToggle} aria-expanded={!closed} onClick={()=>toggleCollapsed(section.id)}><ChevronRight className={closed?'':styles.expanded}/><strong>{section.name}</strong></button>
        <small>{section.items.filter(persona=>selected.has(persona.id)).length}/{section.items.length}</small>
      </header>
      {!closed&&[...section.items].sort((left,right)=>left.name.localeCompare(right.name)).map(persona=>{const participant=roomMap.get(persona.id)??{persona,reasoning_effort_override:null};return <div key={persona.id} className={`${styles.agentRow} ${selected.has(persona.id)?styles.selected:""}`}><label><input type="checkbox" checked={selected.has(persona.id)} onChange={()=>onToggle(persona.id)}/><Avatar label={persona.name} color={persona.color}/><span className={styles.agentIdentity}><span className={styles.agentName}><strong>{persona.name}</strong><HarnessIcon type={persona.harness_type}/></span><small>@{persona.handle} · {personaModelName(persona,catalog)}</small></span></label>{selected.has(persona.id)&&roomMap.has(persona.id)&&<ReasoningEffortChip participant={participant} catalog={catalog} onChange={value=>onUpdateReasoning?.(persona.id,value)}/>}</div>})}
    </section>;
  })}</>;
}
function toggleSet(current:Set<string>,id:string){const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next}

function AgentPicker({title,description,personas,catalog,groups,selected,onToggle,onClose,onSubmit,submitting,error,submitLabel,roomPersonas,onUpdateReasoning}:{title:string;description:string;personas:Persona[];catalog?:HarnessCatalog;groups:PersonaGroup[];selected:Set<string>;onToggle:(id:string)=>void;onClose:()=>void;onSubmit:()=>void;submitting:boolean;error?:string;submitLabel:string;roomPersonas?:RoomPersona[];onUpdateReasoning?:(personaId:string,value:string|null)=>Promise<unknown>}){return <div className={styles.root}><Dialog title={title} description={description} onClose={onClose} labelledBy="agent-picker-title" footer={<><small>Selected: {selected.size}</small><Button onClick={onClose}>Cancel</Button><Button variant="primary" onClick={onSubmit} disabled={submitting}>{submitting?'Saving…':submitLabel}</Button></>}><div className={styles.agentOptions}>{personas.length?<GroupedOptions personas={personas} catalog={catalog} groups={groups} selected={selected} onToggle={onToggle} roomPersonas={roomPersonas} onUpdateReasoning={onUpdateReasoning}/>:<p className="muted">No agents are available. Create one in the Agents section.</p>}</div>{error&&<Alert className={styles.alert}>{error}</Alert>}</Dialog></div>}

export function CreateRoomDialog({personas,catalog,groups,projects,onClose,onCreated}:{personas:Persona[];catalog?:HarnessCatalog;groups:PersonaGroup[];projects?:LocalProject[];onClose:()=>void;onCreated:(personaIds:string[],projectId:string|null)=>Promise<void>}){const[projectId,setProjectId]=useState('');const [showProject,setShowProject]=useState(false);const [selected,setSelected]=useState(()=>new Set<string>());const [saving,setSaving]=useState(false);const [error,setError]=useState<string>();const submit=async()=>{setSaving(true);setError(undefined);try{await onCreated([...selected],projectId||null);onClose()}catch(e){setError(e instanceof Error?e.message:String(e));setSaving(false)}};return <div className={styles.root}><Dialog title="New room" description="Choose agents and optionally a project. The room will be named from your first message." onClose={onClose} labelledBy="create-room-title" footer={<><small>Selected: {selected.size}</small><Button onClick={onClose}>Cancel</Button><Button variant="primary" onClick={()=>void submit()} disabled={saving}>{saving?'Creating…':'Create room'}</Button></>}><div className={styles.roomBasics}>{showProject?<label>Project<select aria-label="Project" autoFocus value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">No project</option>{projects?.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select><small>Agents receive this folder as guidance; their permissions do not change.</small></label>:<button type="button" autoFocus className={styles.addProjectButton} aria-expanded={showProject} onClick={()=>setShowProject(true)}><Plus aria-hidden="true"/>Add project</button>}</div><h3 className={styles.sectionTitle}>ROOM AGENTS</h3><div className={`${styles.agentOptions} ${styles.roomAgents}`}><GroupedOptions personas={personas} catalog={catalog} groups={groups} selected={selected} onToggle={id=>setSelected(current=>toggleSet(current,id))}/></div>{error&&<Alert className={styles.alert}>{error}</Alert>}</Dialog></div>}

export function RoomProjectDialog({room,projects,onClose,onSave}:{room:Room;projects:LocalProject[];onClose:()=>void;onSave:(projectId:string|null)=>Promise<void>}){const[selected,setSelected]=useState(room.project?.id??''),[saving,setSaving]=useState(false),[error,setError]=useState<string>();const save=async()=>{setSaving(true);setError(undefined);try{await onSave(selected||null);onClose();}catch(issue){setError(issue instanceof Error?issue.message:String(issue));setSaving(false);}};return <Dialog title="Room project" description="Choose the local folder agents should prefer for new runs." onClose={onClose} footer={<><Button onClick={onClose}>Cancel</Button><Button variant="primary" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save project'}</Button></>}><div className={styles.projectForm}><label>Recommended project<select autoFocus value={selected} onChange={event=>setSelected(event.target.value)}><option value="">No project</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name} — {project.path}</option>)}</select></label><small>This affects new runs only. Retries retain the project snapshot from their original run.</small>{error&&<Alert tone="error">{error}</Alert>}</div></Dialog>}

export function RoomAgentManager({personas,catalog,groups,roomPersonas,onUpdateReasoning,onClose,onSave}:{personas:Persona[];catalog?:HarnessCatalog;groups:PersonaGroup[];roomPersonas:RoomPersona[];onUpdateReasoning:(personaId:string,value:string|null)=>Promise<unknown>;onClose:()=>void;onSave:(ids:Set<string>)=>Promise<void>}){const [selected,setSelected]=useState(()=>new Set(roomPersonas.map(item=>item.persona.id)));const [saving,setSaving]=useState(false);const [error,setError]=useState<string>();const submit=async()=>{setSaving(true);setError(undefined);try{await onSave(selected);onClose()}catch(e){setError(e instanceof Error?e.message:String(e));setSaving(false)}};return <AgentPicker title="Room agents" description="Only connected agents can be mentioned and respond in this room." personas={personas} catalog={catalog} groups={groups} selected={selected} onToggle={id=>setSelected(current=>toggleSet(current,id))} onClose={onClose} onSubmit={()=>void submit()} submitting={saving} error={error} submitLabel="Save agents" roomPersonas={roomPersonas} onUpdateReasoning={onUpdateReasoning}/>}
