import {useEffect,useRef,useState} from 'react';
import {ChevronRight} from 'lucide-react';
import {HarnessIcon,personaModelName,type HarnessCatalog} from '../../entities/harness';
import type {Persona} from '../../entities/persona';
import type {PersonaGroup} from '../../entities/persona-group';
import type {RoomPersona} from '@agenvyl/contracts';
import {ReasoningEffortChip} from '../reasoning-effort';
import {Alert,Avatar,Button,Dialog,Input} from '../../shared/ui';
import styles from './RoomDialogs.module.css';

function GroupCheckbox({items,label,selected,onToggle}:{items:Persona[];label:string;selected:Set<string>;onToggle:()=>void}){const ref=useRef<HTMLInputElement>(null);const count=items.filter(item=>selected.has(item.id)).length;useEffect(()=>{if(ref.current)ref.current.indeterminate=count>0&&count<items.length},[count,items.length]);return <input ref={ref} type="checkbox" aria-label={`Select the entire ${label} group`} checked={Boolean(items.length)&&count===items.length} onChange={onToggle}/>}
function GroupedOptions({personas,catalog,groups,selected,onToggle,roomPersonas=[],onUpdateReasoning}:{personas:Persona[];catalog?:HarnessCatalog;groups:PersonaGroup[];selected:Set<string>;onToggle:(id:string)=>void;roomPersonas?:RoomPersona[];onUpdateReasoning?:(personaId:string,value:string|null)=>Promise<unknown>}){
  const sections=[...groups.map(group=>({id:group.id,name:group.name,items:personas.filter(p=>p.group_id===group.id)})),{id:'ungrouped',name:'Ungrouped',items:personas.filter(p=>!p.group_id)}].filter(section=>section.items.length);
  const roomMap=new Map(roomPersonas.map(item=>[item.persona.id,item]));
  const [collapsed,setCollapsed]=useState(()=>new Set(sections.filter(section=>!section.items.some(persona=>selected.has(persona.id))).map(section=>section.id)));
  const toggleCollapsed=(id:string)=>setCollapsed(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next});
  return <>{sections.map(section=>{
    const all=section.items.every(persona=>selected.has(persona.id));
    const closed=collapsed.has(section.id);
    return <section className={styles.agentGroup} key={section.id}>
      <header>
        <GroupCheckbox items={section.items} label={section.name} selected={selected} onToggle={()=>section.items.forEach(persona=>{if(all?selected.has(persona.id):!selected.has(persona.id))onToggle(persona.id)})}/>
        <button type="button" className={styles.groupToggle} aria-expanded={!closed} onClick={()=>toggleCollapsed(section.id)}><ChevronRight className={closed?'':styles.expanded}/><strong>{section.name}</strong></button>
        <small>{section.items.filter(persona=>selected.has(persona.id)).length}/{section.items.length}</small>
      </header>
      {!closed&&[...section.items].sort((left,right)=>left.name.localeCompare(right.name)).map(persona=>{const participant=roomMap.get(persona.id)??{persona,reasoning_effort_override:null};return <div key={persona.id} className={`${styles.agentRow} ${selected.has(persona.id)?styles.selected:""}`}><label><input type="checkbox" checked={selected.has(persona.id)} onChange={()=>onToggle(persona.id)}/><Avatar label={persona.name} color={persona.color}/><span className={styles.agentIdentity}><span className={styles.agentName}><strong>{persona.name}</strong><HarnessIcon type={persona.harness_type}/></span><small>@{persona.handle} · {personaModelName(persona,catalog)}</small></span></label>{selected.has(persona.id)&&roomMap.has(persona.id)&&<ReasoningEffortChip participant={participant} catalog={catalog} onChange={value=>onUpdateReasoning?.(persona.id,value)}/>}</div>})}
    </section>;
  })}</>;
}
function toggleSet(current:Set<string>,id:string){const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next}

function AgentPicker({title,description,personas,catalog,groups,selected,onToggle,onClose,onSubmit,submitting,error,submitLabel,roomPersonas,onUpdateReasoning}:{title:string;description:string;personas:Persona[];catalog?:HarnessCatalog;groups:PersonaGroup[];selected:Set<string>;onToggle:(id:string)=>void;onClose:()=>void;onSubmit:()=>void;submitting:boolean;error?:string;submitLabel:string;roomPersonas?:RoomPersona[];onUpdateReasoning?:(personaId:string,value:string|null)=>Promise<unknown>}){return <div className={styles.root}><Dialog title={title} description={description} onClose={onClose} labelledBy="agent-picker-title" footer={<><small>Selected: {selected.size}</small><Button onClick={onClose}>Cancel</Button><Button variant="primary" onClick={onSubmit} disabled={submitting}>{submitting?'Saving…':submitLabel}</Button></>}><div className={styles.agentOptions}>{personas.length?<GroupedOptions personas={personas} catalog={catalog} groups={groups} selected={selected} onToggle={onToggle} roomPersonas={roomPersonas} onUpdateReasoning={onUpdateReasoning}/>:<p className="muted">No agents are available. Create one in the Agents section.</p>}</div>{error&&<Alert className={styles.alert}>{error}</Alert>}</Dialog></div>}

export function CreateRoomDialog({personas,catalog,groups,onClose,onCreated}:{personas:Persona[];catalog?:HarnessCatalog;groups:PersonaGroup[];onClose:()=>void;onCreated:(title:string,personaIds:string[])=>Promise<void>}){const [title,setTitle]=useState('');const [selected,setSelected]=useState(()=>new Set<string>());const [saving,setSaving]=useState(false);const [error,setError]=useState<string>();const submit=async()=>{if(!title.trim()){setError('Enter a room name.');return}setSaving(true);setError(undefined);try{await onCreated(title.trim(),[...selected]);onClose()}catch(e){setError(e instanceof Error?e.message:String(e));setSaving(false)}};return <div className={styles.root}><Dialog title="New room" description="Name the room and add the agents you need." onClose={onClose} labelledBy="create-room-title" footer={<><small>Selected: {selected.size}</small><Button onClick={onClose}>Cancel</Button><Button variant="primary" onClick={()=>void submit()} disabled={saving}>{saving?'Creating…':'Create room'}</Button></>}><label className={styles.roomTitle}>Name<Input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void submit()}} placeholder="For example, Release 2.0"/></label><h3 className={styles.sectionTitle}>ROOM AGENTS</h3><div className={`${styles.agentOptions} ${styles.roomAgents}`}><GroupedOptions personas={personas} catalog={catalog} groups={groups} selected={selected} onToggle={id=>setSelected(current=>toggleSet(current,id))}/></div>{error&&<Alert className={styles.alert}>{error}</Alert>}</Dialog></div>}

export function RoomAgentManager({personas,catalog,groups,roomPersonas,onUpdateReasoning,onClose,onSave}:{personas:Persona[];catalog?:HarnessCatalog;groups:PersonaGroup[];roomPersonas:RoomPersona[];onUpdateReasoning:(personaId:string,value:string|null)=>Promise<unknown>;onClose:()=>void;onSave:(ids:Set<string>)=>Promise<void>}){const [selected,setSelected]=useState(()=>new Set(roomPersonas.map(item=>item.persona.id)));const [saving,setSaving]=useState(false);const [error,setError]=useState<string>();const submit=async()=>{setSaving(true);setError(undefined);try{await onSave(selected);onClose()}catch(e){setError(e instanceof Error?e.message:String(e));setSaving(false)}};return <AgentPicker title="Room agents" description="Only connected agents can be mentioned and respond in this room." personas={personas} catalog={catalog} groups={groups} selected={selected} onToggle={id=>setSelected(current=>toggleSet(current,id))} onClose={onClose} onSubmit={()=>void submit()} submitting={saving} error={error} submitLabel="Save agents" roomPersonas={roomPersonas} onUpdateReasoning={onUpdateReasoning}/>}
