import type { Database } from '../../infrastructure/database/Database.js';
import type { PersonaRepository } from '../personas/personas.repository.js';
import type { Room } from '../../types.js';
import type { Run, ToolActivity } from '@agenvyl/contracts';
import {number,text,toMessage,toRoom,toTimelineRun} from '../../infrastructure/database/rowMappers.js';
import type {WorkspaceRepository} from '../workspace/workspace.repository.js';

export class RoomRepository {
  constructor(private readonly database:Database,private readonly personas:PersonaRepository,private readonly workspace:WorkspaceRepository){}
  async exists(id:string){return Boolean((await this.database.sql`SELECT 1 FROM rooms WHERE id=${id} AND deleted_at IS NULL`)[0]);}
  async list(includeDeleted=false):Promise<Room[]>{const rows=includeDeleted?await this.database.sql`SELECT r.id,r.title,r.created_at,r.deleted_at,COUNT(DISTINCT rp.persona_id)::int participant_count,(SELECT created_at FROM room_messages m WHERE m.room_id=r.id ORDER BY created_at DESC LIMIT 1) last_message_at,(SELECT text FROM room_messages m WHERE m.room_id=r.id ORDER BY created_at DESC LIMIT 1) last_message_text FROM rooms r LEFT JOIN room_participants rp ON rp.room_id=r.id GROUP BY r.id ORDER BY r.deleted_at NULLS FIRST,COALESCE((SELECT MAX(created_at) FROM room_messages m WHERE m.room_id=r.id),r.created_at) DESC`:await this.database.sql`SELECT r.id,r.title,r.created_at,r.deleted_at,COUNT(DISTINCT rp.persona_id)::int participant_count,(SELECT created_at FROM room_messages m WHERE m.room_id=r.id ORDER BY created_at DESC LIMIT 1) last_message_at,(SELECT text FROM room_messages m WHERE m.room_id=r.id ORDER BY created_at DESC LIMIT 1) last_message_text FROM rooms r LEFT JOIN room_participants rp ON rp.room_id=r.id WHERE r.deleted_at IS NULL GROUP BY r.id ORDER BY COALESCE((SELECT MAX(created_at) FROM room_messages m WHERE m.room_id=r.id),r.created_at) DESC`;return rows.map(toRoom);}
  async timeline(roomId:string,before:string|undefined,requestedLimit:number){
    const limit=Math.max(1,Math.min(requestedLimit,100));
    return this.database.sql.begin('read only isolation level repeatable read',async tx=>{
      const room=(await tx`SELECT event_sequence FROM rooms WHERE id=${roomId}`)[0];
      if(!room)return undefined;
      const cursor=before?(await tx`SELECT created_at,id FROM room_messages WHERE room_id=${roomId} AND id=${before}`)[0]:undefined;
      if(before&&!cursor)return undefined;
      const rows=cursor
        ?await tx`SELECT id,text,created_at,targets,run_ids,author_profile_id,author_display_name,author_handle,addressed_to_all FROM room_messages WHERE room_id=${roomId} AND (created_at,id)<(${cursor.created_at as Date},${cursor.id as string}) ORDER BY created_at DESC,id DESC LIMIT ${limit+1}`
        :await tx`SELECT id,text,created_at,targets,run_ids,author_profile_id,author_display_name,author_handle,addressed_to_all FROM room_messages WHERE room_id=${roomId} ORDER BY created_at DESC,id DESC LIMIT ${limit+1}`;
      const hasMore=rows.length>limit,messageRows=rows.slice(0,limit).reverse(),messageIds=messageRows.map(row=>text(row.id)),attachmentMap=await this.workspace.messageAttachments(messageIds,tx),messages=messageRows.map(row=>toMessage(row,attachmentMap.get(text(row.id))??[]));
      const runRows=messageIds.length?await tx`SELECT id,message_id,persona_handle,requested_model,harness_instance_id,harness_type,model_id,mode_id,status,upstream_status,usage,text,reasoning,error,error_code,retry_of_run_id,response_slot_id,connector_execution_id,connector_epoch,connector_cursor,(ROW_NUMBER() OVER(PARTITION BY response_slot_id ORDER BY created_at,id))::int attempt_number,created_at FROM agent_runs WHERE message_id=ANY(${messageIds}) ORDER BY created_at,id`:[];
      const runIds=runRows.map(row=>text(row.id));
      const eventRows=runIds.length?await tx`SELECT type,payload FROM room_events WHERE room_id=${roomId} AND sequence<=${Number(room.event_sequence)} AND type=ANY(${['tool.updated','request.created','request.resolved']}) AND payload->>'runId'=ANY(${runIds}) ORDER BY sequence`:[];
      const extras=new Map<string,{tools:ToolActivity[];request?:Run['request']}>();
      for(const event of eventRows){if(!event.payload||typeof event.payload!=='object')continue;const payload=event.payload as Record<string,unknown>,runId=typeof payload.runId==='string'?payload.runId:undefined;if(!runId)continue;const extra=extras.get(runId)??{tools:[]},tool=payload.tool;if(event.type==='tool.updated'&&isTool(tool)){const prior=extra.tools.find(item=>item.id===tool.id),merged={...prior,...tool,detail:tool.detail||prior?.detail||'',...(tool.input?{input:tool.input}:prior?.input?{input:prior.input}:{})};extra.tools=[...extra.tools.filter(item=>item.id!==tool.id),merged];}if(event.type==='request.created'&&(payload.kind==='approval'||payload.kind==='clarification')){const choices=Array.isArray(payload.choices)?payload.choices.filter((choice):choice is string=>typeof choice==='string'):[];extra.request={kind:payload.kind,prompt:typeof payload.prompt==='string'?payload.prompt:'',...(choices.length?{choices}:{})};}if(event.type==='request.resolved'&&extra.request&&typeof payload.resolution==='string')extra.request.resolved=payload.resolution;extras.set(runId,extra);}
      const selectedRows=messageIds.length?await tx`SELECT id,selected_run_id FROM response_slots WHERE message_id=ANY(${messageIds}) AND selected_run_id IS NOT NULL`:[];
      const artifactMap=await this.workspace.artifacts(runIds,tx),embedMap=await this.workspace.runEmbeds(runIds,tx);
      return{messages,runs:runRows.map(row=>{const id=text(row.id),extra=extras.get(id);return toTimelineRun(row,extra?.tools??[],extra?.request,artifactMap.get(id)??[],embedMap.get(id)??[]);}),selectedRuns:Object.fromEntries(selectedRows.map(row=>[text(row.id),text(row.selected_run_id)])),lastSequence:number(room.event_sequence),hasMore,nextCursor:hasMore?messages[0]?.id:undefined};
    });
  }
  async create(title:string,personaIds:string[]){const id=crypto.randomUUID(),now=new Date().toISOString();await this.database.transaction(async tx=>{await tx`INSERT INTO rooms(id,title,created_at) VALUES(${id},${title},${now})`;for(const pid of new Set(personaIds)){const p=await this.personas.find(pid,tx);if(!p||p.archived_at)throw new Error('persona_unavailable');await tx`INSERT INTO room_participants VALUES(${id},${pid})`;}});return(await this.list()).find(r=>r.id===id)!;}
  async rename(id:string,title:string){const rows=await this.database.sql`UPDATE rooms SET title=${title} WHERE id=${id} RETURNING id`;return rows.length?(await this.list()).find(r=>r.id===id):undefined;}
  async delete(id:string){return this.database.transaction(async tx=>{if(!(await tx`SELECT 1 FROM rooms WHERE id=${id} AND deleted_at IS NULL FOR UPDATE`).length)return'not_found' as const;if((await tx`SELECT 1 FROM agent_runs WHERE room_id=${id} AND status=ANY(${['queued','streaming','stopping','waiting_approval','waiting_clarification']}) LIMIT 1`).length)return'busy' as const;await tx`UPDATE rooms SET deleted_at=now() WHERE id=${id}`;return'deleted' as const;});}
  async restore(id:string){const row=(await this.database.sql`UPDATE rooms SET deleted_at=NULL WHERE id=${id} AND deleted_at IS NOT NULL RETURNING id`)[0];return Boolean(row);}
  async purge(id:string){return this.database.transaction(async tx=>{if(!(await tx`SELECT 1 FROM rooms WHERE id=${id} AND deleted_at IS NOT NULL FOR UPDATE`).length)return'not_found' as const;await tx`DELETE FROM room_events WHERE room_id=${id}`;await tx`UPDATE response_slots SET selected_run_id=NULL WHERE message_id IN(SELECT id FROM room_messages WHERE room_id=${id})`;await tx`UPDATE agent_runs SET response_slot_id=NULL WHERE room_id=${id}`;await tx`DELETE FROM agent_runs WHERE room_id=${id}`;await tx`DELETE FROM response_slots WHERE message_id IN(SELECT id FROM room_messages WHERE room_id=${id})`;await tx`DELETE FROM room_messages WHERE room_id=${id}`;await tx`DELETE FROM room_participants WHERE room_id=${id}`;await tx`DELETE FROM rooms WHERE id=${id}`;return'purged' as const;});}
  async setParticipant(roomId:string,personaId:string,present:boolean){if(!await this.exists(roomId))return'room_not_found' as const;const p=await this.personas.find(personaId);if(!p)return'persona_not_found' as const;if(p.archived_at)return'persona_archived' as const;if(present)await this.database.sql`INSERT INTO room_participants VALUES(${roomId},${personaId}) ON CONFLICT DO NOTHING`;else await this.database.sql`DELETE FROM room_participants WHERE room_id=${roomId} AND persona_id=${personaId}`;return'ok' as const;}
}

function isTool(value:unknown):value is ToolActivity{return Boolean(value&&typeof value==='object'&&typeof(value as {id?:unknown}).id==='string'&&typeof(value as {name?:unknown}).name==='string'&&typeof(value as {detail?:unknown}).detail==='string'&&((value as {input?:unknown}).input===undefined||typeof(value as {input?:unknown}).input==='string')&&['started','progress','completed'].includes(String((value as {status?:unknown}).status)));}
