import type {FastifyInstance} from 'fastify';
import {assignRoomProjectBodySchema,createRoomBodySchema,participantListResponseSchema,participantParamsSchema,renameRoomBodySchema,roomConversationRoutingStateResponseSchema,roomListResponseSchema,roomParamsSchema,roomResponseSchema,roomTimelineQuerySchema,roomTimelineResponseSchema,roomPersonaResponseSchema,roomWorkflowStateResponseSchema,updateRoomConversationRoutingBodySchema,updateRoomPersonaBodySchema,updateRoomWorkflowModeBodySchema} from '../../shared/validation/routeSchemas.js';
import type {RoomsService} from './rooms.service.js';
import type {AssignRoomProjectRequest,CreateRoomRequest,RenameRoomRequest,UpdateRoomConversationRoutingRequest,UpdateRoomPersonaRequest,UpdateRoomWorkflowModeRequest} from '@agenvyl/contracts';
export async function registerRoomRoutes(app:FastifyInstance,rooms:RoomsService,conversationRouting=false){
  app.get<{Querystring:{deleted?:string}}>('/api/v1/rooms',{schema:{response:{200:roomListResponseSchema}}},request=>rooms.list(request.query.deleted==='true'));
  app.get<{Params:{roomId:string};Querystring:{before?:string;limit?:string}}>('/api/v1/rooms/:roomId/timeline',{schema:{params:roomParamsSchema,querystring:roomTimelineQuerySchema,response:{200:roomTimelineResponseSchema}}},request=>rooms.timeline(request.params.roomId,request.query.before,Number(request.query.limit??30)));
  app.put<{Params:{roomId:string};Body:UpdateRoomWorkflowModeRequest}>('/api/v1/rooms/:roomId/workflow-mode',{schema:{params:roomParamsSchema,body:updateRoomWorkflowModeBodySchema,response:{200:roomWorkflowStateResponseSchema}}},request=>rooms.updateWorkflowMode(request.params.roomId,request.body.workflow_mode));
  if(conversationRouting)app.put<{Params:{roomId:string};Body:UpdateRoomConversationRoutingRequest}>('/api/v1/rooms/:roomId/conversation-routing',{schema:{params:roomParamsSchema,body:updateRoomConversationRoutingBodySchema,response:{200:roomConversationRoutingStateResponseSchema}}},request=>rooms.updateConversationRoutingMode(request.params.roomId,request.body.conversation_routing_mode));
  app.post<{Body:CreateRoomRequest}>('/api/v1/rooms',{schema:{body:createRoomBodySchema,response:{201:roomResponseSchema}}},async(request,reply)=>reply.code(201).send(await rooms.create({title:request.body.title,personaIds:request.body.persona_ids,projectId:request.body.project_id})));
  app.patch<{Params:{roomId:string};Body:RenameRoomRequest}>('/api/v1/rooms/:roomId',{schema:{params:roomParamsSchema,body:renameRoomBodySchema,response:{200:roomResponseSchema}}},request=>rooms.rename(request.params.roomId,request.body.title));
  app.put<{Params:{roomId:string};Body:AssignRoomProjectRequest}>('/api/v1/rooms/:roomId/project',{schema:{params:roomParamsSchema,body:assignRoomProjectBodySchema,response:{200:roomResponseSchema}}},request=>rooms.assignProject(request.params.roomId,request.body.project_id));
  app.delete<{Params:{roomId:string};Querystring:{permanent?:string}}>('/api/v1/rooms/:roomId',{schema:{params:roomParamsSchema}},async(request,reply)=>{if(request.query.permanent==='true')await rooms.purge(request.params.roomId);else await rooms.delete(request.params.roomId);return reply.code(204).send();});
  app.post<{Params:{roomId:string}}>('/api/v1/rooms/:roomId/restore',{schema:{params:roomParamsSchema}},request=>rooms.restore(request.params.roomId));
  app.put<{Params:{roomId:string;personaId:string}}>('/api/v1/rooms/:roomId/participants/:personaId',{schema:{params:participantParamsSchema}},request=>rooms.setParticipant(request.params.roomId,request.params.personaId,true));
  app.delete<{Params:{roomId:string;personaId:string}}>('/api/v1/rooms/:roomId/participants/:personaId',{schema:{params:participantParamsSchema}},request=>rooms.setParticipant(request.params.roomId,request.params.personaId,false));
  app.get<{Params:{roomId:string}}>('/api/v1/rooms/:roomId/participants',{schema:{params:roomParamsSchema,response:{200:participantListResponseSchema}}},request=>rooms.participants(request.params.roomId));
  app.patch<{Params:{roomId:string;personaId:string};Body:UpdateRoomPersonaRequest}>('/api/v1/rooms/:roomId/participants/:personaId',{schema:{params:participantParamsSchema,body:updateRoomPersonaBodySchema,response:{200:roomPersonaResponseSchema}}},request=>rooms.updateParticipantReasoning(request.params.roomId,request.params.personaId,request.body.reasoning_effort_override));
}
