import type { Database, QueryContext } from '../../infrastructure/database/Database.js';
import type { Persona, PersonaVersion } from '../../types.js';
import { toPersona, toPersonaVersion } from '../../infrastructure/database/rowMappers.js';

export class PersonaRepository {
  constructor(private readonly database: Database) {}
  async list(roomId?:string,includeArchived=false):Promise<Persona[]>{const db=this.database.sql;const rows=roomId?await db`SELECT p.* FROM personas p JOIN room_participants rp ON rp.persona_id=p.id WHERE rp.room_id=${roomId} ${includeArchived?db``:db`AND p.archived_at IS NULL`} ORDER BY p.created_at`:await db`SELECT p.* FROM personas p WHERE ${includeArchived?db`TRUE`:db`p.archived_at IS NULL`} ORDER BY p.created_at`;return rows.map(toPersona);}
  async find(id:string,db:QueryContext=this.database.sql):Promise<Persona|undefined>{const row=(await db`SELECT * FROM personas WHERE id=${id}`)[0];return row?toPersona(row):undefined;}
  async version(id:string,db:QueryContext=this.database.sql):Promise<PersonaVersion|undefined>{const row=(await db`SELECT * FROM persona_versions WHERE id=${id}`)[0];return row?toPersonaVersion(row):undefined;}
  async detail(id:string){const p=await this.find(id);if(!p)return;return{...p,system_prompt:(await this.version(p.current_version_id))?.system_prompt??''};}
  async create(input:{handle:string;name:string;room_id?:string;role?:string;color?:string;requested_model:string;harness_instance_id:string;harness_type:string;model_id:string;mode_id:string|null;system_prompt?:string;group_id?:string|null}){const now=new Date().toISOString(),id=crypto.randomUUID(),vid=crypto.randomUUID();await this.database.transaction(async tx=>{await tx`INSERT INTO personas(id,handle,name,role,color,requested_model,effective_model,harness_instance_id,harness_type,model_id,mode_id,current_version_id,group_id,created_at,updated_at) VALUES(${id},${input.handle},${input.name},${input.role??''},${input.color??'#64748b'},${input.requested_model},NULL,${input.harness_instance_id},${input.harness_type},${input.model_id},${input.mode_id},${vid},${input.group_id??null},${now},${now})`;await tx`INSERT INTO persona_versions(id,persona_id,version,requested_model,system_prompt,created_at,harness_instance_id,harness_type,model_id,mode_id) VALUES(${vid},${id},1,${input.requested_model},${input.system_prompt??''},${now},${input.harness_instance_id},${input.harness_type},${input.model_id},${input.mode_id})`;if(input.room_id)await tx`INSERT INTO room_participants VALUES(${input.room_id},${id})`;});return this.detail(id);}
  async update(id:string,input:Partial<{handle:string;name:string;role:string;color:string;requested_model:string;harness_instance_id:string;harness_type:string;model_id:string;mode_id:string|null;system_prompt:string;group_id:string|null}>){const old=await this.find(id);if(!old)return;const prior=(await this.version(old.current_version_id))!,now=new Date().toISOString(),vid=crypto.randomUUID(),requestedModel=input.requested_model??old.requested_model??old.model_id,harnessInstanceId=input.harness_instance_id??old.harness_instance_id,harnessType=input.harness_type??old.harness_type,modelId=input.model_id??old.model_id,modeId=input.mode_id===undefined?old.mode_id:input.mode_id;await this.database.transaction(async tx=>{const [{n}]=await tx`SELECT COALESCE(MAX(version),0)::int+1 n FROM persona_versions WHERE persona_id=${id}`;await tx`INSERT INTO persona_versions(id,persona_id,version,requested_model,system_prompt,created_at,harness_instance_id,harness_type,model_id,mode_id) VALUES(${vid},${id},${n as number},${requestedModel},${input.system_prompt??prior.system_prompt},${now},${harnessInstanceId},${harnessType},${modelId},${modeId})`;await tx`UPDATE personas SET handle=${input.handle?.toLowerCase()??old.handle},name=${input.name??old.name},role=${input.role??old.role},color=${input.color??old.color},requested_model=${requestedModel},harness_instance_id=${harnessInstanceId},harness_type=${harnessType},model_id=${modelId},mode_id=${modeId},group_id=${input.group_id===undefined?old.group_id:input.group_id},effective_model=NULL,current_version_id=${vid},updated_at=${now} WHERE id=${id}`;});return this.find(id);}
  async setArchived(id:string,archived:boolean){const p=await this.find(id);if(!p)return'not_found' as const;if(Boolean(p.archived_at)===archived)return'conflict' as const;await this.database.sql`UPDATE personas SET archived_at=${archived?new Date().toISOString():null},updated_at=now() WHERE id=${id}`;return this.detail(id);}
  async delete(id:string){return this.database.transaction(async tx=>{if(!(await tx`SELECT 1 FROM personas WHERE id=${id} FOR UPDATE`).length)return{status:'not_found' as const};const [d]=await tx`SELECT COUNT(*)::int agent_runs FROM agent_runs WHERE persona_id=${id}`;if(Number(d.agent_runs))return{status:'in_use' as const,dependencies:d};await tx`DELETE FROM personas WHERE id=${id}`;return{status:'deleted' as const};});}
  async setEffectiveModel(id:string,model:string|null){await this.database.sql`UPDATE personas SET effective_model=${model} WHERE id=${id}`;}
}
