import {describe,expect,it,vi} from 'vitest';
import {initialState,roomReducer,type RoomEvent,type RoomState} from '../../../entities/room';
import {ApiError} from '../../../shared/api';
import {FakeRoomGateway,HttpRoomGateway} from './RoomGateway';

describe('FakeRoomGateway',()=>{it('emits parallel runs that complete',()=>{vi.useFakeTimers();const gateway=new FakeRoomGateway();let state:RoomState=initialState;gateway.subscribe(event=>{state=roomReducer(state,event)});gateway.demo('parallel');expect(state.runOrder).toHaveLength(2);vi.runAllTimers();expect(state.runOrder.map(id=>state.runs[id].status)).toEqual(['completed','completed']);gateway.dispose();vi.useRealTimers()})});

describe('HttpRoomGateway',()=>{
  class Socket{static last:Socket;onopen?:()=>void;onmessage?:(event:{data:string})=>void;onclose?:()=>void;readyState=1;constructor(){Socket.last=this}close(){this.onclose?.()}}
  it('buffers replay events before React subscribes',()=>{vi.stubGlobal('location',{protocol:'http:',host:'example.test'});vi.stubGlobal('WebSocket',Socket);const gateway=new HttpRoomGateway();const event={id:'event-1',sequence:1,type:'run.created',payload:{id:'run-1',messageId:'message-1',agent:'coder',harnessInstanceId:'local-hermes',harnessType:'hermes',modelId:'sol',executionProfile:{workflowMode:'work',requestedReasoningEffort:null,reasoningEffort:null,reasoningEffortFallback:false,reasoningEffortSource:'auto',planEnforcement:null,permissionProfileId:null,agentVariantId:null,implementationPlanVersionId:null},status:'queued',text:'',tools:[]}} as RoomEvent;Socket.last.onmessage?.({data:JSON.stringify(event)});const received:RoomEvent[]=[];gateway.subscribe(item=>received.push(item));expect(received[0]).toEqual(event);gateway.dispose();vi.unstubAllGlobals()});
  it('surfaces structured send errors and preserves retry ids',async()=>{vi.stubGlobal('location',{protocol:'http:',host:'example.test'});vi.stubGlobal('WebSocket',Socket);const request=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({error:'unknown_target',message:'Bad target'}),{status:400,headers:{'content-type':'application/json'}}));vi.stubGlobal('fetch',request);const gateway=new HttpRoomGateway('room-1');await expect(gateway.send('hello',['missing'],'12345678-1234-1234-1234-123456789abc')).rejects.toEqual(expect.objectContaining<Partial<ApiError>>({status:400,code:'unknown_target'}));expect(request).toHaveBeenCalledWith('/api/v1/rooms/room-1/messages',expect.objectContaining({body:expect.stringContaining('12345678-1234-1234-1234-123456789abc')}));gateway.dispose();vi.unstubAllGlobals()});
});
