import {describe,expect,it,vi} from 'vitest';
import {initialState,roomReducer,type RoomEvent,type RoomState} from '../../../entities/room';
import {ApiError} from '../../../shared/api';
import {FakeRoomGateway,HttpRoomGateway} from './RoomGateway';

describe('FakeRoomGateway',()=>{
  it('emits parallel runs that complete',()=>{vi.useFakeTimers();const gateway=new FakeRoomGateway();let state:RoomState=initialState;gateway.subscribe(event=>{state=roomReducer(state,event)});gateway.demo('parallel');expect(state.runOrder).toHaveLength(2);vi.runAllTimers();expect(state.runOrder.map(id=>state.runs[id].status)).toEqual(['completed','completed']);gateway.dispose();vi.useRealTimers()});
  it('starts a newly created demo room in Plan and mirrors automatic naming',async()=>{const gateway=new FakeRoomGateway(true,'plan');let state:RoomState=initialState;gateway.subscribe(event=>{state=roomReducer(state,event)});await gateway.send('Hello. Fix the OAuth redirect.',['architect']);expect(state.workflowMode).toBe('plan');expect(state.runs[state.runOrder[0]!]?.executionProfile).toMatchObject({workflowMode:'plan',planEnforcement:'instruction_only'});expect(state.latestTitle).toBe('Fix the OAuth redirect.');gateway.dispose();});
});

describe('HttpRoomGateway',()=>{
  class Socket{static last?:Socket;onopen?:()=>void;onmessage?:(event:{data:string})=>void;onclose?:()=>void;readyState=1;constructor(){Socket.last=this}close(){this.onclose?.()}}
  it('connects only after React subscribes',()=>{Socket.last=undefined;vi.stubGlobal('location',{protocol:'http:',host:'example.test'});vi.stubGlobal('WebSocket',Socket);const gateway=new HttpRoomGateway();expect(Socket.last).toBeUndefined();const event={id:'event-1',sequence:1,type:'run.created',payload:{id:'run-1',messageId:'message-1',agent:'coder',harnessInstanceId:'local-hermes',harnessType:'hermes',modelId:'sol',executionProfile:{workflowMode:'work',requestedReasoningEffort:null,reasoningEffort:null,reasoningEffortFallback:false,reasoningEffortSource:'auto',planEnforcement:null,permissionProfileId:null,agentVariantId:null},status:'queued',text:'',tools:[],interventions:[]}} as RoomEvent;const received:RoomEvent[]=[];gateway.subscribe(item=>received.push(item));Socket.last!.onmessage?.({data:JSON.stringify(event)});expect(received[0]).toEqual(event);gateway.dispose();vi.unstubAllGlobals()});
  it('surfaces structured send errors and preserves retry ids',async()=>{vi.stubGlobal('location',{protocol:'http:',host:'example.test'});vi.stubGlobal('WebSocket',Socket);const request=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({error:'unknown_target',message:'Bad target'}),{status:400,headers:{'content-type':'application/json'}}));vi.stubGlobal('fetch',request);const gateway=new HttpRoomGateway('room-1');await expect(gateway.send('hello',['missing'],'12345678-1234-1234-1234-123456789abc')).rejects.toEqual(expect.objectContaining<Partial<ApiError>>({status:400,code:'unknown_target'}));expect(request).toHaveBeenCalledWith('/api/v1/rooms/room-1/messages',expect.objectContaining({body:expect.stringContaining('12345678-1234-1234-1234-123456789abc')}));gateway.dispose();vi.unstubAllGlobals()});
  it('promotes a queued room message through its message-scoped endpoint',async()=>{vi.stubGlobal('location',{protocol:'http:',host:'example.test'});vi.stubGlobal('WebSocket',Socket);const request=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({}),{status:202,headers:{'content-type':'application/json'}}));vi.stubGlobal('fetch',request);const gateway=new HttpRoomGateway('room-1');await gateway.applyQueuedNow('message-1');expect(request).toHaveBeenCalledWith('/api/v1/rooms/room-1/messages/message-1/apply-now',expect.objectContaining({method:'POST'}));gateway.dispose();vi.unstubAllGlobals()});
});
