import {describe,expect,it,vi} from 'vitest';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {commandInvocation,discoverHarnesses,runCodexLoginStatus,runVersion} from './discovery.js';

describe('harness discovery',()=>{
  it('marks only attachable safe harnesses and keeps AGY behind a separate boundary',async()=>{
    const run=vi.fn(async(command:string)=>command==='agy'?{found:true,command,version:'1.1.3'}:{found:true,command,version:command==='codex'?'0.100.0':'1.0.0'}),request=vi.fn<typeof fetch>(async url=>new Response('',{status:String(url).includes('8642')?200:503}));
    const result=await discoverHarnesses({env:{},run,request,codexAuth:vi.fn(async()=>false)});
    expect(result.candidates.map(candidate=>[candidate.type,candidate.safeToSelect,candidate.cli.compatible])).toEqual([['hermes',true,true],['opencode',true,true],['antigravity',false,true],['codex',false,false]]);
    expect(result.candidates[2].warning).toContain('separate');
  });
  it('resolves and executes npm .cmd shims on Windows',async()=>{const execute=vi.fn(async(file:string)=>file==='where.exe'?{stdout:'C:\\Users\\Vladimir\\AppData\\Roaming\\npm\\opencode.cmd\r\n',stderr:''}:{stdout:'opencode 1.2.3\r\n',stderr:''});await expect(runVersion('opencode',{platform:'win32',env:{ComSpec:'C:\\Windows\\System32\\cmd.exe'},execute})).resolves.toEqual({found:true,command:'opencode',version:'1.2.3'});expect(execute.mock.calls).toEqual([['where.exe',['opencode'],expect.any(Object)],['C:\\Windows\\System32\\cmd.exe',['/d','/s','/c','""C:\\Users\\Vladimir\\AppData\\Roaming\\npm\\opencode.cmd" --version"'],expect.objectContaining({windowsVerbatimArguments:true})]]);});
  it('builds a safe managed-server invocation for Windows npm shims',()=>{expect(commandInvocation('C:\\Users\\Vladimir\\AppData\\Roaming\\npm\\opencode.cmd',['serve','--hostname','127.0.0.1','--port','4096'],'win32',{ComSpec:'cmd.exe'})).toEqual({file:'cmd.exe',args:['/d','/s','/c','""C:\\Users\\Vladimir\\AppData\\Roaming\\npm\\opencode.cmd" serve --hostname 127.0.0.1 --port 4096"'],windowsVerbatimArguments:true});});
  it('selects Codex only at the stable version floor with a valid login',async()=>{const request=vi.fn<typeof fetch>(async()=>new Response('',{status:503}));const result=await discoverHarnesses({env:{},request,run:vi.fn(async command=>({found:true,command,version:command==='codex'?'0.145.0':'1.1.3'})),codexAuth:vi.fn(async()=>true)});expect(result.candidates.find(candidate=>candidate.type==='codex')).toMatchObject({safeToSelect:true,cli:{compatible:true}});const prerelease=await discoverHarnesses({env:{},request,run:vi.fn(async command=>({found:true,command,version:command==='codex'?'0.145.0-alpha.18':'1.1.3'})),codexAuth:vi.fn(async()=>true)});expect(prerelease.candidates.find(candidate=>candidate.type==='codex')).toMatchObject({safeToSelect:false,cli:{compatible:false}});});
  it('checks login status through Windows command shims',async()=>{const execute=vi.fn(async(file:string)=>file==='where.exe'?{stdout:'C:\\npm\\codex.cmd\r\n',stderr:''}:{stdout:'Logged in using ChatGPT',stderr:''});await expect(runCodexLoginStatus('codex',{platform:'win32',env:{ComSpec:'cmd.exe'},execute})).resolves.toBe(true);expect(execute.mock.calls[1]?.[1]).toEqual(['/d','/s','/c','""C:\\npm\\codex.cmd" login status"']);});
  it.runIf(process.platform==='win32')('executes a real Windows command shim with Node argument quoting',async()=>{const root=await mkdtemp(join(tmpdir(),'agenvyl-command-shim-')),command=join(root,'test harness.cmd');try{await writeFile(command,'@echo off\r\necho harness 7.8.9\r\n');await expect(runVersion(command)).resolves.toEqual({found:true,command,version:'7.8.9'});}finally{await rm(root,{recursive:true,force:true});}});
});
