import {mkdtemp,mkdir,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import {CodexConnectorAdapter} from '../adapters/codex/adapter.js';
import type {AdapterExecutionEvent,AdapterStartExecutionRequest} from '../adapter.js';

const live=process.env.RUN_CODEX_LIVE_SMOKE==='1';
describe.runIf(live)('Codex CLI live smoke',()=>{
  let root='';const adapter=new CodexConnectorAdapter({command:process.env.AGENVYL_CONNECTOR_CODEX_COMMAND});
  beforeAll(async()=>{root=await mkdtemp(join(tmpdir(),'agenvyl-codex-live-'));await mkdir(join(root,'room'));});
  afterAll(async()=>{await adapter.close();await rm(root,{recursive:true,force:true});});
  it('covers catalog, exact text, tool/file change, redirect, usage and cancel',async()=>{
    const catalog=await adapter.catalog(),model=catalog.models[0];expect(model).toBeDefined();expect(catalog.controls.permissionProfiles.map(item=>item.id)).toContain('workspace-write');
    const exact=await run('exact','Reply with exactly AGENVYL_CODEX_OK.');expect(exact.text.trim()).toBe('AGENVYL_CODEX_OK');expect(exact.events.some(event=>event.type==='usage.updated')).toBe(true);
    const file=await run('file','Create a UTF-8 file named codex-live.txt containing exactly live-ok, then finish.');expect(await readFile(join(root,'room','codex-live.txt'),'utf8')).toBe('live-ok');expect(file.events.some(event=>event.type==='tool.started')).toBe(true);
    const redirected=await adapter.start({...request('redirect','Run a shell command that waits for 20 seconds, then reply with exactly AGENVYL_CODEX_OLD.'),modelId:model!.id}),redirectEvents:AdapterExecutionEvent[]=[],redirectIterator=adapter.events(redirected)[Symbol.asyncIterator]();
    let intervention:Promise<void>|undefined,applied=false,redirectedText='';
    while(true){const next=await redirectIterator.next();if(next.done)break;const event=next.value;redirectEvents.push(event);if(event.type==='request.opened')await adapter.resolveRequest(redirected,event.payload.request,event.payload.request.kind==='approval'?{resolution:'once'}:{answers:Object.fromEntries((event.payload.request.questions??[]).map(question=>[question.id,[question.options?.[0]?.label??'yes']]))});if(event.type==='tool.started'&&!intervention){intervention=adapter.intervene(redirected,{interventionId:'11111111-1111-4111-8111-111111111111',text:'Reply with exactly AGENVYL_CODEX_REDIRECT_OK.'});void intervention.catch(()=>{});}if(event.type==='execution.intervention.applied')applied=true;else if(applied&&event.type==='output.text.delta')redirectedText+=event.payload.text;if(['execution.completed','execution.cancelled','execution.failed'].includes(event.type))break;}
    expect(intervention).toBeDefined();await intervention;expect(redirectEvents.some(event=>event.type==='execution.intervention.applied')).toBe(true);expect(redirectedText.trim()).toBe('AGENVYL_CODEX_REDIRECT_OK');expect(redirectEvents.at(-1)?.type).toBe('execution.completed');
    const cancellation=await adapter.start({...request('cancel','Run a shell command that waits for 20 seconds, then reply.'),modelId:model!.id}),stream=adapter.events(cancellation)[Symbol.asyncIterator]();let stop:Promise<void>|undefined,terminal:AdapterExecutionEvent|undefined;for(let index=0;index<100;index++){const next=await stream.next();if(next.done)break;const event=next.value;if(event.type==='request.opened')await adapter.resolveRequest(cancellation,event.payload.request,event.payload.request.kind==='approval'?{resolution:'once'}:{answers:Object.fromEntries((event.payload.request.questions??[]).map(question=>[question.id,[question.options?.[0]?.label??'yes']]))});if(event.type==='tool.started'&&!stop){stop=adapter.stop(cancellation);void stop.catch(()=>{});}if(['execution.cancelled','execution.completed','execution.failed'].includes(event.type)){terminal=event;break;}}expect(stop).toBeDefined();await stop;expect(terminal?.type).toBe('execution.cancelled');
  },180_000);
  const request=(id:string,message:string):AdapterStartExecutionRequest=>({executionId:id,harnessInstanceId:'local-codex',modelId:'',executionProfile:{workflowMode:'work',reasoningEffort:null,permissionProfileId:'workspace-write',agentVariantId:null,planEnforcement:null},workspace:{roomId:'room',relativePath:'.',absolutePath:join(root,'room')},input:{systemPrompt:'Follow the request precisely.',history:[],message}});
  const run=async(id:string,message:string)=>{const catalog=await adapter.catalog(),model=catalog.models[0];if(!model)throw new Error('Codex has no visible model');const execution=await adapter.start({...request(id,message),modelId:model.id}),events:AdapterExecutionEvent[]=[],iterator=adapter.events(execution)[Symbol.asyncIterator]();while(true){const next=await iterator.next();if(next.done)break;const event=next.value;events.push(event);if(event.type==='request.opened')await adapter.resolveRequest(execution,event.payload.request,event.payload.request.kind==='approval'?{resolution:'once'}:{answers:Object.fromEntries((event.payload.request.questions??[]).map(question=>[question.id,[question.options?.[0]?.label??'yes']]))});}return{text:events.filter((event):event is Extract<AdapterExecutionEvent,{type:'output.text.delta'}>=>event.type==='output.text.delta').map(event=>event.payload.text).join(''),events};};
});
