import {describe,expect,it} from 'vitest';
import type {Run} from '../../run';
import {initialState,roomReducer,type RoomEvent} from './roomState';

const run:Run={id:'r1',messageId:'m1',agent:'coder',harnessInstanceId:'local-hermes',harnessType:'hermes',modelId:'sol',executionProfile:{workflowMode:'work',requestedReasoningEffort:null,reasoningEffort:null,reasoningEffortFallback:false,reasoningEffortSource:'auto',planEnforcement:null,permissionProfileId:null,agentVariantId:null},status:'queued',text:'',tools:[],interventions:[]};
const event=(sequence:number,type:RoomEvent['type'],payload:unknown)=>({id:`e${sequence}`,sequence,type,payload}) as RoomEvent;

describe('roomReducer',()=>{
  it('streams content, tools, usage, and terminal state',()=>{let state=roomReducer(initialState,event(1,'run.created',run));state=roomReducer(state,event(2,'run.reasoning.delta',{runId:'r1',text:'thinking'}));state=roomReducer(state,event(3,'run.delta',{runId:'r1',text:'hello'}));state=roomReducer(state,event(4,'tool.updated',{runId:'r1',tool:{id:'t',name:'read',detail:'file',status:'completed'}}));state=roomReducer(state,event(5,'run.usage',{runId:'r1',usage:{inputTokens:20,outputTokens:5}}));state=roomReducer(state,event(6,'run.status',{runId:'r1',status:'completed'}));expect(state.runs.r1).toMatchObject({reasoning:'thinking',text:'hello',status:'completed',usage:{inputTokens:20},tools:[{id:'t'}]})});
  it('updates room participants and workflow mode without timeline messages',()=>{const participant={persona:{id:'coder'},reasoning_effort_override:'high'};let state=roomReducer(initialState,event(1,'room.participant.updated',participant));state=roomReducer(state,event(2,'room.workflow_mode.updated',{workflowMode:'plan'}));expect(state.participantUpdates.coder).toEqual(participant);expect(state.workflowMode).toBe('plan');expect(state.messages).toEqual([])});
  it('does not treat plan.md workspace changes as workflow state',()=>{const state=roomReducer({...initialState,workflowMode:'plan'},event(1,'workspace.changed',{change:'updated',entry:{id:'entry-1',path:'plan.md',name:'plan.md',kind:'file',size:10,mime_type:'text/markdown',updated_at:'2026-07-22',current_version_id:'current-version'}}));expect(state.workflowMode).toBe('plan');expect(state.messages).toEqual([]);});
  it('tracks finalization and publication metadata',()=>{let state=roomReducer(initialState,event(1,'run.created',run));state=roomReducer(state,event(2,'run.status',{runId:'r1',status:'finalizing'}));expect(state.runs.r1.status).toBe('finalizing');const workspaceResult={base_snapshot_id:'base',result_snapshot_id:'result',published_snapshot_id:'published',capture_status:'complete',publish_status:'partially_published',conflict_count:2,errors:[]} as const;state=roomReducer(state,event(3,'run.workspace.finalized',{runId:'r1',workspaceResult}));expect(state.runs.r1.workspaceResult).toEqual(workspaceResult);});
  it('keeps parallel requests addressable until each matching request is resolved',()=>{let state=roomReducer(initialState,event(1,'run.created',run));state=roomReducer(state,event(2,'request.created',{runId:'r1',requestId:'approval-1',kind:'approval',prompt:'Allow read?'}));state=roomReducer(state,event(3,'request.created',{runId:'r1',requestId:'approval-2',kind:'approval',prompt:'Allow bash?'}));state=roomReducer(state,event(4,'request.resolved',{runId:'r1',requestId:'approval-2',resolution:'answered'}));expect(state.runs.r1).toMatchObject({status:'waiting_approval',requests:[{id:'approval-1'},{id:'approval-2',resolved:'answered'}]});expect(state.runs.r1.requests?.[0]?.resolved).toBeUndefined();state=roomReducer(state,event(5,'request.resolved',{runId:'r1',requestId:'approval-1',resolution:'answered'}));expect(state.runs.r1.status).toBe('streaming');});
  it('resets the visible answer only when a redirect is applied',()=>{let state=roomReducer(initialState,event(1,'run.created',{...run,status:'streaming',text:'Old answer',reasoning:'Old reasoning'}));state=roomReducer(state,event(2,'run.intervention.updated',{runId:'r1',intervention:{id:'redirect-1',text:'Change direction',status:'pending'}}));expect(state.runs.r1).toMatchObject({text:'Old answer',interventions:[{status:'pending'}]});state=roomReducer(state,event(3,'run.intervention.updated',{runId:'r1',intervention:{id:'redirect-1',text:'Change direction',status:'applied',supersededText:'Old answer'}}));expect(state.runs.r1).toMatchObject({text:'',reasoning:'',interventions:[{status:'applied',supersededText:'Old answer'}]});state=roomReducer(state,event(4,'run.delta',{runId:'r1',text:'New answer'}));expect(state.runs.r1.text).toBe('New answer');});
  it('ignores replayed duplicate sequence',()=>{const state=roomReducer(initialState,event(1,'run.created',run));expect(roomReducer(state,event(1,'run.delta',{runId:'r1',text:'duplicate'}))).toBe(state)});
});
