import type { Message } from '../../message';
import type { Run } from '../../run';
import { upsertToolActivity, type Room, type RoomPersona, type ServerRoomEvent, type TimelinePage, type UpstreamStatus, type WorkflowMode } from '@agenvyl/contracts';
export type Connection = 'connecting' | 'connected' | 'reconnecting' | 'replaying';
export type { TimelinePage } from '@agenvyl/contracts';
export type RoomState = { messages: Message[]; messageCount:number; runs: Record<string, Run>; runOrder: string[]; selectedRuns:Record<string,string>; participantUpdates:Record<string,RoomPersona>; latestTitle?:string; workflowMode:WorkflowMode; connection: Connection; lastSequence: number; selectedRunId?: string; appliedPatch: boolean; hydrated:boolean; hasMore:boolean; nextCursor?:string };

export type RoomEvent = ServerRoomEvent | { id: string; sequence: number; type: 'connection.changed'; payload: { status: Connection } };

export const initialState: RoomState = { messages: [], messageCount:0, runs: {}, runOrder: [], selectedRuns:{}, participantUpdates:{}, workflowMode:'work', connection: 'connecting', lastSequence: 0, appliedPatch: false, hydrated:false, hasMore:false };

export function stateFromTimeline(page:TimelinePage):RoomState{return{...initialState,messages:page.messages,messageCount:page.messageCount,runs:Object.fromEntries(page.runs.map(run=>[run.id,run])),runOrder:page.runs.map(run=>run.id),selectedRuns:page.selectedRuns,workflowMode:page.workflowMode,lastSequence:page.lastSequence,hydrated:true,hasMore:page.hasMore,nextCursor:page.nextCursor};}
export function prependTimeline(state:RoomState,page:TimelinePage):RoomState{const known=new Set(state.messages.map(message=>message.id));const runs={...state.runs};for(const run of page.runs)runs[run.id]??=run;return{...state,messages:[...page.messages.filter(message=>!known.has(message.id)),...state.messages],runs,runOrder:[...page.runs.map(run=>run.id).filter(id=>!state.runs[id]),...state.runOrder],selectedRuns:{...page.selectedRuns,...state.selectedRuns},hasMore:page.hasMore,nextCursor:page.nextCursor};}
export const applyRoomTitle=(rooms:Room[]|undefined,roomId:string,title:string)=>rooms?.map(room=>room.id===roomId?{...room,title}:room);

export function roomReducer(state: RoomState, event: RoomEvent): RoomState {
  if (event.type === 'connection.changed') return { ...state, connection: event.payload.status };
  if (event.sequence <= state.lastSequence) return state;
  const base = { ...state, lastSequence: event.sequence };
  switch (event.type) {
    case 'message.created': return { ...base, messages: [...state.messages, event.payload], messageCount:state.messageCount+1 };
    case 'run.created': {const isRepeatedResponse=Boolean(event.payload.retryOfRunId||event.payload.continuedFromRunId);return { ...base, messages:state.messages.map(message=>message.id===event.payload.messageId&&!message.runIds.includes(event.payload.id)?{...message,runIds:[...message.runIds,event.payload.id]}:message), messageCount:state.messageCount+(isRepeatedResponse?0:1), runs: { ...state.runs, [event.payload.id]: {...event.payload,reasoning:event.payload.reasoning??''} }, runOrder: [...state.runOrder, event.payload.id] };}
    case 'run.selected':return {...base,selectedRuns:{...state.selectedRuns,[event.payload.responseSlotId]:event.payload.runId}};
    case 'run.delta': { const run = state.runs[event.payload.runId]; return run ? { ...base, runs: { ...state.runs, [run.id]: { ...run, text: run.text + event.payload.text } } } : base; }
    case 'run.reasoning.delta': { const run = state.runs[event.payload.runId]; return run ? { ...base, runs: { ...state.runs, [run.id]: { ...run, reasoning: (run.reasoning??'') + event.payload.text } } } : base; }
    case 'run.status': { const run = state.runs[event.payload.runId];const terminal=['completed','failed','cancelled'].includes(event.payload.status); return run ? { ...base, runs: { ...state.runs, [run.id]: { ...run, status: event.payload.status, ...(terminal?{upstreamStatus:undefined,interventions:run.interventions.map(item=>item.status==='pending'?{...item,status:'failed' as const,error:item.error??'Run ended before the instruction was applied'}:item)}:{}), error: event.payload.error, errorCode:event.payload.errorCode } },...(event.payload.status==='completed'?{selectedRuns:{...state.selectedRuns,[run.responseSlotId??run.retryOfRunId??run.id]:run.id}}:{}) } : base; }
    case 'run.upstream_status': { const run=state.runs[event.payload.runId];if(!run)return base;if(event.payload.state==='recovered')return{...base,runs:{...state.runs,[run.id]:{...run,upstreamStatus:undefined}}};const{runId:_runId,...payload}=event.payload,upstreamStatus=payload as UpstreamStatus;return{...base,runs:{...state.runs,[run.id]:{...run,upstreamStatus}}};}
    case 'run.usage':{const run=state.runs[event.payload.runId];return run?{...base,runs:{...state.runs,[run.id]:{...run,usage:event.payload.usage}}}:base;}
    case 'run.project.updated':{const run=state.runs[event.payload.runId];return run?{...base,runs:{...state.runs,[run.id]:{...run,recommendedProject:event.payload.project}}}:base;}
    case 'tool.updated': { const run = state.runs[event.payload.runId]; if (!run) return base; return { ...base, runs: { ...state.runs, [run.id]: { ...run, tools:upsertToolActivity(run.tools,event.payload.tool) } } }; }
    case 'request.created': { const run = state.runs[event.payload.runId];if(!run)return base;const request={id:event.payload.requestId,kind:event.payload.kind,prompt:event.payload.prompt,...(event.payload.directory?{directory:event.payload.directory}:{}),...(event.payload.choices?.length?{choices:event.payload.choices}:{}),...(event.payload.questions?.length?{questions:event.payload.questions}:{}),...(event.payload.elicitation?{elicitation:event.payload.elicitation}:{}),...(event.payload.autoResolutionMs?{autoResolutionMs:event.payload.autoResolutionMs}:{})};return{...base,runs:{...state.runs,[run.id]:{...run,status:event.payload.kind==='approval'?'waiting_approval':'waiting_clarification',requests:[...(run.requests??[]).filter(item=>item.id!==request.id),request]}}}; }
    case 'request.resolved': { const run=state.runs[event.payload.runId];if(!run)return base;const requests=(run.requests??[]).map(request=>request.id===event.payload.requestId?{...request,resolved:event.payload.resolution}:request),pending=requests.filter(request=>!request.resolved),status=pending.some(request=>request.kind==='clarification')?'waiting_clarification':pending.length?'waiting_approval':'streaming';return{...base,runs:{...state.runs,[run.id]:{...run,status,requests}}}; }
    case 'run.intervention.updated': { const run=state.runs[event.payload.runId];if(!run)return base;const incoming=event.payload.intervention,priorIndex=run.interventions.findIndex(item=>item.id===incoming.id),prior=priorIndex>=0?run.interventions[priorIndex]:undefined,precedingText=incoming.precedingText??incoming.supersededText??prior?.precedingText??prior?.supersededText,intervention={...prior,...incoming,...(precedingText!==undefined?{precedingText}:{})};delete intervention.supersededText;const interventions=priorIndex>=0?run.interventions.map((item,index)=>index===priorIndex?intervention:item):[...run.interventions,intervention],firstPending=incoming.status==='pending'&&!prior,reasoning=firstPending&&run.reasoning&&!run.reasoning.endsWith('\n\n')?`${run.reasoning}\n\n`:run.reasoning;return{...base,runs:{...state.runs,[run.id]:{...run,interventions,...(firstPending?{text:'',reasoning}:{})}}}; }
    case 'artifact.created':{const run=state.runs[event.payload.runId];return run?{...base,runs:{...state.runs,[run.id]:{...run,artifacts:[...(run.artifacts??[]).filter(item=>item.version_id!==event.payload.artifact.version_id),event.payload.artifact]}}}:base;}
    case 'run.embeds':{const run=state.runs[event.payload.runId];return run?{...base,runs:{...state.runs,[run.id]:{...run,embeds:event.payload.embeds}}}:base;}
    case 'run.workspace.finalized':{const run=state.runs[event.payload.runId];return run?{...base,runs:{...state.runs,[run.id]:{...run,workspaceResult:event.payload.workspaceResult,...(event.payload.artifacts?{artifacts:event.payload.artifacts}:{}),...(event.payload.artifactSummary?{artifactSummary:event.payload.artifactSummary}:{}),...(event.payload.staticPreview?{staticPreview:event.payload.staticPreview}:{}),...(event.payload.staticPreviewStatus?{staticPreviewStatus:event.payload.staticPreviewStatus}:{})}}}:base;}
    case 'room.participant.updated':return{...base,participantUpdates:{...state.participantUpdates,[event.payload.persona.id]:event.payload}};
    case 'room.title.updated':return{...base,latestTitle:event.payload.title};
    case 'room.workflow_mode.updated':return{...base,workflowMode:event.payload.workflowMode};
  }
  return base;
}
