import {describe,expect,it} from 'vitest';
import type {Run} from '../../run';
import {initialState,roomReducer,type RoomEvent} from './roomState';

const run:Run={id:'r1',messageId:'m1',agent:'coder',harnessInstanceId:'local-hermes',harnessType:'hermes',modelId:'sol',executionProfile:{workflowMode:'work',requestedReasoningEffort:null,reasoningEffort:null,reasoningEffortFallback:false,reasoningEffortSource:'auto',planEnforcement:null,permissionProfileId:null,agentVariantId:null,implementationPlanVersionId:null},status:'queued',text:'',tools:[]};
const event=(sequence:number,type:RoomEvent['type'],payload:unknown)=>({id:`e${sequence}`,sequence,type,payload}) as RoomEvent;

describe('roomReducer',()=>{
  it('streams content, tools, usage, and terminal state',()=>{let state=roomReducer(initialState,event(1,'run.created',run));state=roomReducer(state,event(2,'run.reasoning.delta',{runId:'r1',text:'thinking'}));state=roomReducer(state,event(3,'run.delta',{runId:'r1',text:'hello'}));state=roomReducer(state,event(4,'tool.updated',{runId:'r1',tool:{id:'t',name:'read',detail:'file',status:'completed'}}));state=roomReducer(state,event(5,'run.usage',{runId:'r1',usage:{inputTokens:20,outputTokens:5}}));state=roomReducer(state,event(6,'run.status',{runId:'r1',status:'completed'}));expect(state.runs.r1).toMatchObject({reasoning:'thinking',text:'hello',status:'completed',usage:{inputTokens:20},tools:[{id:'t'}]})});
  it('updates room participant and plan state without timeline messages',()=>{const plan={entry_id:'entry-1',version_id:'version-1'},participant={persona:{id:'coder'},reasoning_effort_override:'high'};let state=roomReducer(initialState,event(1,'room.participant.updated',participant));state=roomReducer(state,event(2,'room.plan.approval.updated',{approved:plan}));expect(state.participantUpdates.coder).toEqual(participant);expect(state.executionState).toEqual({plan:{path:'plan.md',current:null,approved:plan}});expect(state.messages).toEqual([])});
  it('tracks plan.md current versions independently from approval',()=>{const approved={entry_id:'entry-1',version_id:'approved-version'},base={...initialState,executionState:{...initialState.executionState,plan:{...initialState.executionState.plan,approved}}};const state=roomReducer(base,event(1,'workspace.changed',{change:'updated',entry:{id:'entry-1',path:'plan.md',name:'plan.md',kind:'file',size:10,mime_type:'text/markdown',updated_at:'2026-07-22',current_version_id:'current-version'}}));expect(state.executionState.plan).toEqual({path:'plan.md',current:{entry_id:'entry-1',version_id:'current-version'},approved});});
  it('ignores replayed duplicate sequence',()=>{const state=roomReducer(initialState,event(1,'run.created',run));expect(roomReducer(state,event(1,'run.delta',{runId:'r1',text:'duplicate'}))).toBe(state)});
});
