import {describe,expect,it} from 'vitest';
import type {Run} from '../../run';
import {applyRoomTitle,initialState,roomReducer,type RoomEvent} from './roomState';

const run:Run={id:'r1',messageId:'m1',agent:'coder',harnessInstanceId:'local-hermes',harnessType:'hermes',modelId:'sol',executionProfile:{workflowMode:'work',requestedReasoningEffort:null,reasoningEffort:null,reasoningEffortFallback:false,reasoningEffortSource:'auto',planEnforcement:null,permissionProfileId:null,agentVariantId:null},status:'queued',text:'',tools:[],interventions:[]};
const event=(sequence:number,type:RoomEvent['type'],payload:unknown)=>({id:`e${sequence}`,sequence,type,payload}) as RoomEvent;

describe('roomReducer',()=>{
  it('streams content, tools, usage, and terminal state',()=>{let state=roomReducer(initialState,event(1,'run.created',run));state=roomReducer(state,event(2,'run.reasoning.delta',{runId:'r1',text:'thinking'}));state=roomReducer(state,event(3,'run.delta',{runId:'r1',text:'hello'}));state=roomReducer(state,event(4,'tool.updated',{runId:'r1',tool:{id:'t',name:'read',detail:'file',status:'completed'}}));state=roomReducer(state,event(5,'run.usage',{runId:'r1',usage:{inputTokens:20,outputTokens:5}}));state=roomReducer(state,event(6,'run.status',{runId:'r1',status:'completed'}));expect(state.runs.r1).toMatchObject({reasoning:'thinking',text:'hello',status:'completed',usage:{inputTokens:20},tools:[{id:'t'}]})});
  it('updates room participants and workflow mode without timeline messages',()=>{const participant={persona:{id:'coder'},reasoning_effort_override:'high'};let state=roomReducer(initialState,event(1,'room.participant.updated',participant));state=roomReducer(state,event(2,'room.workflow_mode.updated',{workflowMode:'plan'}));expect(state.participantUpdates.coder).toEqual(participant);expect(state.workflowMode).toBe('plan');expect(state.messages).toEqual([])});
  it('projects durable room title updates',()=>{const state=roomReducer(initialState,event(1,'room.title.updated',{title:'Fix OAuth redirect'}));expect(state.latestTitle).toBe('Fix OAuth redirect');expect(state.messages).toEqual([])});
  it('applies a projected title to the room list used by the header and sidebar',()=>{const rooms=[{id:'room-1',title:'New room'},{id:'room-2',title:'Other'}] as import('@agenvyl/contracts').Room[];expect(applyRoomTitle(rooms,'room-1','Fix OAuth redirect')?.map(room=>room.title)).toEqual(['Fix OAuth redirect','Other']);});
  it('does not treat plan.md workspace changes as workflow state',()=>{const state=roomReducer({...initialState,workflowMode:'plan'},event(1,'workspace.changed',{change:'updated',entry:{id:'entry-1',path:'plan.md',name:'plan.md',kind:'file',size:10,mime_type:'text/markdown',updated_at:'2026-07-22',current_version_id:'current-version'}}));expect(state.workflowMode).toBe('plan');expect(state.messages).toEqual([]);});
  it('tracks Git finalization metadata',()=>{let state=roomReducer(initialState,event(1,'run.created',run));state=roomReducer(state,event(2,'run.status',{runId:'r1',status:'finalizing'}));expect(state.runs.r1.status).toBe('finalizing');const workspaceResult={base_head:'base',result_head:'result',capture_status:'complete',errors:[],updated_at:'2026-08-10T10:00:00.000Z'} as const,artifact={version_id:'v1',path:'src/app.ts',name:'app.ts',size:10,mime_type:'text/typescript',url:'/v1',preview_url:'/v1/preview',change:'created' as const,attribution:'exact' as const},staticPreview={version_id:'preview',path:'dist/index.html',name:'index.html',size:20,mime_type:'text/html',url:'/preview',preview_url:'/run-preview'};state=roomReducer(state,event(3,'run.workspace.finalized',{runId:'r1',workspaceResult,artifacts:[artifact],artifactSummary:{total_count:4,project_count:1,hidden_count:3},staticPreview,staticPreviewStatus:'ready'}));expect(state.runs.r1).toMatchObject({workspaceResult,artifacts:[artifact],artifactSummary:{total_count:4,project_count:1,hidden_count:3},staticPreview,staticPreviewStatus:'ready'});});
  it('keeps parallel requests addressable until each matching request is resolved',()=>{let state=roomReducer(initialState,event(1,'run.created',run));state=roomReducer(state,event(2,'request.created',{runId:'r1',requestId:'approval-1',kind:'approval',prompt:'Allow read?'}));state=roomReducer(state,event(3,'request.created',{runId:'r1',requestId:'approval-2',kind:'approval',prompt:'Allow bash?'}));state=roomReducer(state,event(4,'request.resolved',{runId:'r1',requestId:'approval-2',resolution:'answered'}));expect(state.runs.r1).toMatchObject({status:'waiting_approval',requests:[{id:'approval-1'},{id:'approval-2',resolved:'answered'}]});expect(state.runs.r1.requests?.[0]?.resolved).toBeUndefined();state=roomReducer(state,event(5,'request.resolved',{runId:'r1',requestId:'approval-1',resolution:'answered'}));expect(state.runs.r1.status).toBe('streaming');});
  it('starts a new answer segment when an instruction becomes pending',()=>{
    let state=roomReducer(initialState,event(1,'run.created',{...run,status:'streaming',text:'Old answer',reasoning:'Old reasoning'}));
    state=roomReducer(state,event(2,'run.intervention.updated',{runId:'r1',intervention:{id:'instruction-1',text:'Change direction',status:'pending',precedingText:'Old answer',author:{profileId:'local-user',displayName:'User',handle:'user'},createdAt:'2026-07-20T12:01:00.000Z'}}));
    expect(state.runs.r1).toMatchObject({text:'',reasoning:'Old reasoning\n\n',interventions:[{status:'pending',precedingText:'Old answer'}]});
    state=roomReducer(state,event(3,'run.delta',{runId:'r1',text:'New answer'}));
    state=roomReducer(state,event(4,'run.intervention.updated',{runId:'r1',intervention:{id:'instruction-1',text:'Change direction',status:'applied'}}));
    expect(state.runs.r1).toMatchObject({text:'New answer',reasoning:'Old reasoning\n\n',interventions:[{status:'applied',precedingText:'Old answer',author:{displayName:'User'}}]});
  });
  it('keeps failed and repeated instructions at their original segment boundaries',()=>{
    let state=roomReducer(initialState,event(1,'run.created',{...run,status:'streaming',text:'First'}));
    state=roomReducer(state,event(2,'run.intervention.updated',{runId:'r1',intervention:{id:'instruction-1',text:'Try one',status:'pending',precedingText:'First'}}));
    state=roomReducer(state,event(3,'run.delta',{runId:'r1',text:'Second'}));
    state=roomReducer(state,event(4,'run.intervention.updated',{runId:'r1',intervention:{id:'instruction-1',text:'Try one',status:'failed',error:'Rejected'}}));
    state=roomReducer(state,event(5,'run.intervention.updated',{runId:'r1',intervention:{id:'instruction-2',text:'Try two',status:'pending',precedingText:'Second'}}));
    state=roomReducer(state,event(6,'run.intervention.updated',{runId:'r1',intervention:{id:'instruction-1',text:'Try one',status:'failed',error:'Still rejected'}}));
    expect(state.runs.r1).toMatchObject({text:'',interventions:[{id:'instruction-1',status:'failed',precedingText:'First',error:'Still rejected'},{id:'instruction-2',status:'pending',precedingText:'Second'}]});
  });
  it('ignores replayed duplicate sequence',()=>{const state=roomReducer(initialState,event(1,'run.created',run));expect(roomReducer(state,event(1,'run.delta',{runId:'r1',text:'duplicate'}))).toBe(state)});
});
