import {useEffect,useMemo,useState} from 'react';
import {DndContext,DragOverlay,KeyboardSensor,PointerSensor,TouchSensor,closestCenter,useDroppable,useSensor,useSensors,type DragEndEvent,type DragStartEvent} from '@dnd-kit/core';
import {SortableContext,sortableKeyboardCoordinates,useSortable,verticalListSortingStrategy} from '@dnd-kit/sortable';
import {CSS} from '@dnd-kit/utilities';
import { Archive, ChevronDown, FolderPlus, Search } from 'lucide-react';
import {HarnessIcon,personaModelName,type HarnessCatalog} from '../../entities/harness';
import type {Persona} from '../../entities/persona';
import {personasApi} from '../../entities/persona';
import {personaGroupsApi,type PersonaGroup} from '../../entities/persona-group';
import {Alert,Button,Input} from '../../shared/ui';
import styles from './PersonasScreen.module.css';

const COLLAPSE_KEY='hermes.persona-groups.collapsed';
const groupDragId=(id:string)=>`group:${id}`;
const readCollapsed=()=>{try{return new Set<string>(JSON.parse(localStorage.getItem(COLLAPSE_KEY)??'[]'))}catch{return new Set<string>()}};
const initials=(name:string)=>name.trim().split(/\s+/).slice(0,2).map(part=>part[0]??'').join('').toLocaleUpperCase()||'?';

function PersonaRow({persona,catalog,selected,inRoom,onSelect,onMove,groups}:{persona:Persona;catalog?:HarnessCatalog;selected:boolean;inRoom:boolean;onSelect:()=>void;onMove:(groupId:string|null)=>void;groups:PersonaGroup[]}){
  const [menu,setMenu]=useState(false);
  return <div className={`${styles['persona-row']} ${selected?styles.selected:''}`}>
    <button className={styles['persona-main']} type="button" onClick={onSelect}><i style={{background:persona.color}}>{initials(persona.name)}</i><span><span className={styles['persona-name']}><strong>{persona.name}{inRoom&&<b className={styles['room-dot']} title="In the current room" />}</strong><HarnessIcon type={persona.harness_type}/></span><small>@{persona.handle} · {personaModelName(persona,catalog)}</small></span></button>
    <button className={styles['row-menu-trigger']} type="button" aria-label={`Actions for agent ${persona.name}`} aria-expanded={menu} onClick={()=>setMenu(value=>!value)}>⋮</button>
    {menu&&<div className={styles['row-menu']} role="menu"><strong>Move to…</strong><button type="button" disabled={!persona.group_id} onClick={()=>{onMove(null);setMenu(false)}}>Ungrouped</button>{groups.map(group=><button type="button" key={group.id} disabled={persona.group_id===group.id} onClick={()=>{onMove(group.id);setMenu(false)}}>{group.name}</button>)}</div>}
  </div>;
}

function GroupSection({group,groups,catalog,index,total,items,allCount,closed,selected,roomPersonaIds,query,busy,real,onToggle,onSelect,onMove,onRename,onMoveGroup,onDelete}:{group?:PersonaGroup;groups:PersonaGroup[];catalog?:HarnessCatalog;index:number;total:number;items:Persona[];allCount:number;closed:boolean;selected?:string;roomPersonaIds:Set<string>;query:boolean;busy:boolean;real:boolean;onToggle:()=>void;onSelect:(id:string)=>void;onMove:(id:string,groupId:string|null)=>void;onRename:(group:PersonaGroup,name:string)=>void;onMoveGroup:(group:PersonaGroup,direction:'up'|'down')=>void;onDelete:(group:PersonaGroup)=>void}){
  const [menu,setMenu]=useState(false);const [renaming,setRenaming]=useState(false);const [name,setName]=useState(group?.name??'');
  const sortable=useSortable({id:group?groupDragId(group.id):'sortable:ungrouped',data:{type:group?'group':'drop',groupId:group?.id??null},disabled:!group||query||busy||!real});
  const ungroupedDrop=useDroppable({id:'drop:ungrouped',data:{type:'drop',groupId:null},disabled:Boolean(group)});
  return <section ref={group?sortable.setNodeRef:ungroupedDrop.setNodeRef} className={`${styles['persona-group']} ${(group?sortable.isOver:ungroupedDrop.isOver)?styles['drop-target']:''} ${sortable.isDragging?styles.dragging:''}`} style={{transform:group?CSS.Transform.toString(sortable.transform):undefined,transition:group?sortable.transition:undefined}}>
    <header>
      {renaming&&group?<form className={styles['rename-group']} onSubmit={event=>{event.preventDefault();if(name.trim()){onRename(group,name);setRenaming(false)}}}><Input autoFocus maxLength={80} value={name} onChange={event=>setName(event.target.value)} onKeyDown={event=>{if(event.key==='Escape'){setRenaming(false);setName(group.name)}}}/><button type="submit" disabled={busy||!name.trim()}>✓</button><button type="button" onClick={()=>{setRenaming(false);setName(group.name)}}>×</button></form>:<button type="button" className={styles['group-toggle']} aria-expanded={!closed} onClick={onToggle}><ChevronDown className={`${styles['group-chevron']} ${closed?styles.closed:''}`}/><strong>{group?.name??'Ungrouped'}</strong><small>{query&&items.length!==allCount?`${items.length}/${allCount}`:allCount}</small></button>}
      {group&&real&&!renaming&&<div className={styles['group-menu-wrap']}><button type="button" className={styles['group-menu-trigger']} aria-label={`Actions for group ${group.name}`} aria-expanded={menu} onClick={()=>setMenu(value=>!value)}>⋮</button>{menu&&<div className={styles['group-menu']} role="menu"><button type="button" onClick={()=>{setRenaming(true);setName(group.name);setMenu(false)}}>Rename</button><button type="button" disabled={index===0||busy} onClick={()=>{onMoveGroup(group,'up');setMenu(false)}}>Move up</button><button type="button" disabled={index===total-1||busy} onClick={()=>{onMoveGroup(group,'down');setMenu(false)}}>Move down</button><button type="button" className={styles.danger} disabled={busy} onClick={()=>{onDelete(group);setMenu(false)}}>Delete group…</button></div>}</div>}
    </header>
    {!closed&&<div className={styles['persona-list']}>{items.map(persona=><PersonaRow key={persona.id} persona={persona} catalog={catalog} selected={selected===persona.id} inRoom={roomPersonaIds.has(persona.id)} onSelect={()=>onSelect(persona.id)} onMove={groupId=>onMove(persona.id,groupId)} groups={groups}/>) }{!items.length&&<small className={styles['empty-group']}>{query?'No matches':'This group has no agents yet'}</small>}</div>}
  </section>;
}

export function PersonaCatalog({personas,catalog,groups:sourceGroups,selected,creatingPersona,roomPersonaIds,real,onSelect,onChanged,onPersonaMoved}:{personas:Persona[];catalog?:HarnessCatalog;groups:PersonaGroup[];selected?:string;creatingPersona:boolean;roomPersonaIds:Set<string>;real:boolean;onSelect:(id:string)=>void;onChanged:()=>Promise<void>;onPersonaMoved:(id:string,groupId:string|null)=>void}){
  const [search,setSearch]=useState('');const [collapsed,setCollapsed]=useState(readCollapsed);const [showArchive,setShowArchive]=useState(false);const [creating,setCreating]=useState(false);const [newName,setNewName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<string>();const [active,setActive]=useState<{type:'group';id:string;label:string}>();const [overrides,setOverrides]=useState<Record<string,string|null>>({});
  const [groups,setGroups]=useState(sourceGroups);useEffect(()=>setGroups(sourceGroups),[sourceGroups]);
  const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}),useSensor(TouchSensor,{activationConstraint:{delay:180,tolerance:6}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
  const query=search.trim().toLocaleLowerCase();
  const currentPersonas=useMemo(()=>personas.map(persona=>Object.prototype.hasOwnProperty.call(overrides,persona.id)?{...persona,group_id:overrides[persona.id]}:persona),[personas,overrides]);
  const activePersonas=currentPersonas.filter(persona=>!persona.archived_at).sort((left,right)=>left.name.localeCompare(right.name));const matches=(persona:Persona)=>!query||[persona.name,persona.handle,personaModelName(persona,catalog)].some(value=>value.toLocaleLowerCase().includes(query));
  const mutate=async(action:()=>Promise<unknown>)=>{setBusy(true);setError(undefined);try{await action();await onChanged()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
  const movePersona=async(id:string,groupId:string|null)=>{const persona=currentPersonas.find(item=>item.id===id);if(!persona||persona.group_id===groupId)return;const previous=persona.group_id;setOverrides(value=>({...value,[id]:groupId}));onPersonaMoved(id,groupId);setError(undefined);try{await personasApi.moveToGroup(id,groupId);await onChanged();setOverrides(value=>{const next={...value};delete next[id];return next})}catch(reason){setOverrides(value=>({...value,[id]:previous}));onPersonaMoved(id,previous);setError(reason instanceof Error?reason.message:String(reason))}};
  const reorderGroup=async(from:number,to:number)=>{const previous=groups;const next=[...groups];const [moved]=next.splice(from,1);next.splice(to,0,moved);setGroups(next.map((group,position)=>({...group,position})));setBusy(true);setError(undefined);try{await personaGroupsApi.reorder(moved.id,to);await onChanged()}catch(reason){setGroups(previous);setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
  const toggle=(key:string)=>setCollapsed(current=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);localStorage.setItem(COLLAPSE_KEY,JSON.stringify([...next]));return next});
  const endDrag=(event:DragEndEvent)=>{const activeId=String(event.active.id),overId=event.over?String(event.over.id):'';setActive(undefined);if(!overId)return;if(activeId.startsWith('group:')&&overId.startsWith('group:')&&!query){const from=groups.findIndex(group=>group.id===activeId.slice(6)),to=groups.findIndex(group=>group.id===overId.slice(6));if(from>=0&&to>=0&&from!==to)void reorderGroup(from,to)}};
  const startDrag=(event:DragStartEvent)=>{const id=String(event.active.id);if(id.startsWith('group:')){const group=groups.find(item=>item.id===id.slice(6));if(group)setActive({type:'group',id:group.id,label:group.name})}};
  const sections=groups.map(group=>({group,all:activePersonas.filter(persona=>persona.group_id===group.id),items:activePersonas.filter(persona=>persona.group_id===group.id&&matches(persona))}));const ungrouped=activePersonas.filter(persona=>!persona.group_id);const archived=currentPersonas.filter(persona=>persona.archived_at&&matches(persona)).sort((left,right)=>left.name.localeCompare(right.name));
  return <div className={styles['catalog-panel']} ui-spec-block-id="persona_grouped_list">
    <div className={`${styles['catalog-toolbar']} ${!real?styles.readonly:''}`}>
      <label className={styles['catalog-search']}><Search/><Input aria-label="Search agents" placeholder="Search agents…" value={search} onChange={event=>setSearch(event.target.value)}/></label>
      <button type="button" className={`${styles['toolbar-action']} ${showArchive?styles.selected:''}`} aria-label="Show or hide archive" title="Show or hide archive" onClick={()=>setShowArchive(value=>!value)}><Archive/></button>
      {real&&<button type="button" className={styles['toolbar-action']} aria-label="Create group" title="Create group" onClick={()=>setCreating(true)}><FolderPlus/><span>Group</span></button>}
    </div>
    {creating&&<form className={styles['create-group-form']} onSubmit={event=>{event.preventDefault();if(newName.trim())void mutate(async()=>{await personaGroupsApi.create(newName);setNewName('');setCreating(false)})}}><Input autoFocus aria-label="New group name" placeholder="Group name" maxLength={80} value={newName} onChange={event=>setNewName(event.target.value)} onKeyDown={event=>{if(event.key==='Escape'){setCreating(false);setNewName('')}}}/><Button type="submit" variant="primary" disabled={busy||!newName.trim()}>Create</Button><Button type="button" onClick={()=>{setCreating(false);setNewName('')}}>Cancel</Button></form>}
    {error&&<Alert tone="error">{error}</Alert>}
    {creatingPersona&&<section className={styles['persona-group']}><div className={styles['persona-list']}><div className={`${styles['persona-row']} ${styles['draft-row']} ${styles.selected}`}><span className={styles['persona-main']}><i>?</i><span><strong>New agent</strong><small>draft · not saved</small></span></span></div></div></section>}
    <DndContext sensors={sensors} collisionDetection={closestCenter} onDragStart={startDrag} onDragCancel={()=>setActive(undefined)} onDragEnd={endDrag} accessibility={{screenReaderInstructions:{draggable:'Press Space or Enter to start moving. Use the arrow keys, then press Space or Enter again.'}}}>
      <SortableContext items={groups.map(group=>groupDragId(group.id))} strategy={verticalListSortingStrategy}>{sections.map(({group,all,items},index)=><GroupSection key={group.id} group={group} groups={groups} catalog={catalog} index={index} total={groups.length} items={items} allCount={all.length} closed={!query&&collapsed.has(group.id)} selected={selected} roomPersonaIds={roomPersonaIds} query={Boolean(query)} busy={busy} real={real} onToggle={()=>toggle(group.id)} onSelect={onSelect} onMove={movePersona} onRename={(item,name)=>void mutate(()=>personaGroupsApi.rename(item.id,name))} onMoveGroup={(item,direction)=>void mutate(()=>personaGroupsApi.move(item.id,direction))} onDelete={item=>{if(confirm(`Delete group “${item.name}”?${all.length?` ${all.length} agents will become ungrouped.`:''}`))void mutate(()=>personaGroupsApi.remove(item.id))}}/>)}</SortableContext>
      {(ungrouped.length>0||groups.length===0)&&<GroupSection groups={groups} catalog={catalog} index={groups.length} total={groups.length} items={ungrouped.filter(matches)} allCount={ungrouped.length} closed={!query&&collapsed.has('ungrouped')} selected={selected} roomPersonaIds={roomPersonaIds} query={Boolean(query)} busy={busy} real={real} onToggle={()=>toggle('ungrouped')} onSelect={onSelect} onMove={movePersona} onRename={()=>undefined} onMoveGroup={()=>undefined} onDelete={()=>undefined}/>}
      <DragOverlay>{active&&<div className={styles['drag-overlay']}><span>Group</span><strong>{active.label}</strong></div>}</DragOverlay>
    </DndContext>
    {(showArchive||Boolean(query))&&<section className={`${styles['persona-group']} ${styles.archive}`}><header><button className={styles['group-toggle']} type="button" aria-expanded={Boolean(query)||!collapsed.has('archive')} onClick={()=>toggle('archive')}><ChevronDown className={`${styles['group-chevron']} ${!query&&collapsed.has('archive')?styles.closed:''}`}/><strong>Archive</strong><small>{archived.length}</small></button></header>{(query||!collapsed.has('archive'))&&<div className={styles['persona-list']}>{archived.map(persona=><div className={`${styles['persona-row']} ${styles['is-archived']}`} key={persona.id}><button className={styles['persona-main']} type="button" onClick={()=>onSelect(persona.id)}><i style={{background:persona.color}}>{initials(persona.name)}</i><span><span className={styles['persona-name']}><strong>{persona.name}</strong><HarnessIcon type={persona.harness_type}/></span><small>@{persona.handle} · {personaModelName(persona,catalog)}</small></span></button><button className={styles['row-menu-trigger']} type="button" aria-label={`Open archived agent ${persona.name}`} onClick={()=>onSelect(persona.id)}>⋮</button></div>)}{!archived.length&&<small className={styles['empty-group']}>Archive is empty</small>}</div>}</section>}
  </div>;
}
