export const migrations = [
  { version: 1, name: 'initial', file: '001_initial.sql' },
  { version: 2, name: 'persona_groups', file: '002_persona_groups.sql' },
  { version: 3, name: 'workspace_versions', file: '003_workspace_versions.sql' },
  { version: 4, name: 'run_embeds', file: '004_run_embeds.sql' },
  { version: 5, name: 'run_embed_content_validation', file: '005_run_embed_content_validation.sql' },
  { version: 6, name: 'drop_legacy_session_mappings', file: '006_drop_legacy_session_mappings.sql' },
  { version: 7, name: 'harness_execution_snapshots', file: '007_harness_execution_snapshots.sql' },
  { version: 8, name: 'run_execution_deadlines', file: '008_run_execution_deadlines.sql' },
  { version: 9, name: 'run_reasoning', file: '009_run_reasoning.sql' },
  { version: 10, name: 'local_user_identity', file: '010_local_user_identity.sql' },
  { version: 11, name: 'run_upstream_status', file: '011_run_upstream_status.sql' },
  { version: 12, name: 'run_usage', file: '012_run_usage.sql' },
  { version: 13, name: 'installation_state', file: '013_installation_state.sql' },
  { version: 14, name: 'room_execution_profiles', file: '014_room_execution_profiles.sql' },
  { version: 15, name: 'plan_workspace_artifact', file: '015_plan_workspace_artifact.sql' },
  { version: 16, name: 'persona_reasoning_effort', file: '016_persona_reasoning_effort.sql' },
  { version: 17, name: 'remove_room_reasoning_effort', file: '017_remove_room_reasoning_effort.sql' },
  { version: 18, name: 'workspace_snapshots', file: '018_workspace_snapshots.sql' },
  { version: 19, name: 'workspace_noop_cleanup', file: '019_workspace_noop_cleanup.sql' },
  { version: 20, name: 'workspace_slots', file: '020_workspace_slots.sql' },
  { version: 21, name: 'workspace_stat_cache', file: '021_workspace_stat_cache.sql' },
] as const;
