export type PersonaGroup = { id:string; name:string; position:number; created_at:string; updated_at:string };
export type Persona = { id: string; handle: string; name: string; role: string; color: string; requested_model: string | null; effective_model: string | null; harness_instance_id:string; harness_type:string; model_id:string; permission_profile_id:string|null; agent_variant_id:string|null; default_reasoning_effort:string|null; current_version_id: string; group_id:string|null; created_at: string; updated_at: string; archived_at: string | null };
export type PersonaVersion = { id: string; persona_id: string; version: number; requested_model: string | null; harness_instance_id:string; harness_type:string; model_id:string; permission_profile_id:string|null; agent_variant_id:string|null; default_reasoning_effort:string|null; system_prompt: string; created_at: string };
export type LocalUserProfile = {id:string;displayName:string;handle:string;createdAt:string;updatedAt:string};
export type HumanAuthorSnapshot = {profileId:string;displayName:string;handle:string};
export type RunStatus = WireRunStatus;
export type RoomEvent = { id: string; event_id: string; sequence: number; type: string; payload: unknown };
export type ConversationItem = { role: 'user' | 'assistant'; content: string };
export type Room = WireRoom;
export type RunContext = { id: string; messageId: string; roomId: string; personaVersionId: string; personaHandle?: string; requestedModel: string; harnessInstanceId:string; harnessType:string; modelId:string; executionProfile:import('@agenvyl/contracts').RunExecutionProfileSnapshot; conversationHistory: ConversationItem[]; correlationId?:string; responseText?: string; sessionId?: string; upstreamRunId?: string; connectorExecutionId?:string; executionDeadlineAt?:string; status?:RunStatus; controller?: AbortController; terminal: boolean; started?:boolean; refreshContext?:boolean; stopping?: boolean; waitingFor?: 'approval' | 'clarification' };
import type { Room as WireRoom, RunStatus as WireRunStatus } from '@agenvyl/contracts';
